/* Arbre des trois monothéismes — contenus pédagogiques :
   lexique, références, parcours guidés. */

/* ---------- lexique ----------
   id, t titre, c catégorie, m formes repérées dans les textes (sensibles à la casse ; une forme en minuscule
   est aussi cherchée avec majuscule initiale, sauf cs:true), d définition, n entrée liée de l'arbre,
   auto:false = seulement dans le lexique. */
const GLOSS_CAT = {
  gen:'Notions générales', jud:'Judaïsme', chr:'Christianisme', isl:'Islam',
  his:'Histoire et archéologie', sym:'Dates, signes et abréviations'
};
const GLOSSARY = [
/* dates, signes, abréviations */
{id:"am", t:"AM (anno mundi)", c:"sym", m:["AM"], cs:true, d:"« An du monde » : calendrier juif traditionnel, qui compte les années depuis la création du monde, placée en 3761 av. J.-C. Pour convertir, on retranche l'année AM de 3761 : AM 1948, naissance d'Abraham, correspond à environ 1812 av. J.-C. Ces dates sont symboliques et n'ont pas de valeur historique."},
{id:"trad", t:"trad. (date traditionnelle)", c:"sym", m:["trad."], cs:true, d:"Date donnée par la tradition religieuse (calculs rabbiniques, récits des Églises ou de la Sīra), sans confirmation par les sources historiques."},
{id:"avjc", t:"av. J.-C. · apr. J.-C.", c:"sym", m:[], auto:false, d:"Avant et après Jésus-Christ : l'ère commune, fixée au VIe siècle par le moine Denys le Petit. Jésus est en réalité né quelques années « avant Jésus-Christ », avant la mort d'Hérode en 4 av. J.-C."},
{id:"siecle", t:"Ier, IIe… s.", c:"sym", m:[], auto:false, d:"Siècles en chiffres romains : le IIe s. av. J.-C. va de 200 à 101 av. J.-C. ; le VIIe s. va de 601 à 700. « Xe–XIe s. » signifie du Xe au XIe siècle."},
{id:"tilde", t:"~ (environ)", c:"sym", m:[], auto:false, d:"Date ou nombre approximatif : « ~570 » signifie « vers 570 »."},
{id:"dague", t:"† (mort en)", c:"sym", m:[], auto:false, d:"Année de la mort : « † 62 » signifie « mort en 62 »."},
{id:"union", t:"⚭ (union)", c:"sym", m:[], auto:false, d:"Signe du mariage : « Adam ⚭ Ève » réunit un couple dans une seule entrée de l'arbre."},
{id:"fleche", t:"→ (raccourci)", c:"sym", m:[], auto:false, d:"Dans un nom d'entrée, la flèche résume plusieurs générations ou une évolution : « Koush → Nimrod » (de Koush à son fils Nimrod), « Rūmī → Mevlevis » (du fondateur à l'ordre qui en est issu)."},
{id:"auj", t:"auj. (aujourd'hui)", c:"sym", m:[], auto:false, d:"Le courant ou la communauté existe encore de nos jours : « 1054 – auj. »."},
{id:"langues", t:"héb. · ar. · gr.", c:"sym", m:[], auto:false, d:"Indiquent la langue d'une forme du nom : hébreu, arabe, grec. « Mūsā (ar.) » est le nom arabe de Moïse, tel que l'emploie le Coran."},
{id:"translit", t:"ʿ ʾ ā ḥ ṣ ṭ ẓ (translittération)", c:"sym", m:[], auto:false, d:"Signes savants qui notent les sons de l'arabe et de l'hébreu : ʿ (ʿayn, son guttural), ʾ (hamza, coup de glotte), ā ī ū (voyelles longues), ḥ ṣ ṭ ḍ ẓ (consonnes « emphatiques » ou aspirées). Ils permettent de distinguer des noms proches."},
{id:"incertain", t:"(?) ou « ? »", c:"sym", m:[], auto:false, d:"Identification incertaine ou discutée : « Hūd ? » signifie que le rapprochement avec ce prophète n'est pas sûr."},
{id:"refbible", t:"Références bibliques : Gn 4,8", c:"sym", m:[], auto:false, d:"Livre abrégé, chapitre, verset : « Gn 4,8 » = Genèse, chapitre 4, verset 8 ; « Gn 4,17-18 » = versets 17 à 18 ; « Gn 1–3 » = chapitres 1 à 3 ; « 1 R » = premier livre des Rois. Touchez une référence dans une fiche pour la décoder et ouvrir le passage."},
{id:"refcoran", t:"Références coraniques : Coran 2,127", c:"sym", m:[], auto:false, d:"Sourate (chapitre) puis verset : « Coran 2,127 » = sourate 2 (al-Baqara), verset 127. Le Coran compte 114 sourates. Dans les fiches, une référence entre parenthèses après une mention du Coran se lit de la même façon."},
{id:"reftalmud", t:"Références juives : Shabbat 31a", c:"sym", m:[], auto:false, d:"Talmud : traité, feuillet et face (a = recto, b = verso). Michna : traité, chapitre, paragraphe (« Sanhédrin 4,5 »). Midrash : recueil et section (« Genèse Rabba 38 »)."},

/* notions générales */
{id:"monotheisme", t:"Monothéisme", c:"gen", m:["monothéisme","monothéiste","monothéistes"], d:"Croyance en un Dieu unique. Judaïsme, christianisme et islam sont dits « abrahamiques » parce qu'ils se réclament tous trois d'Abraham. En Israël, le monothéisme strict s'est formulé progressivement, surtout pendant l'Exil à Babylone (VIe s. av. J.-C.)."},
{id:"polytheisme", t:"Polythéisme · païens", c:"gen", m:["polythéisme","polythéistes","païens","païen","païenne"], d:"Culte de plusieurs dieux. « Païen » (du latin paganus, « paysan ») désigne chez les chrétiens les fidèles des anciens cultes ; le Coran parle des « associateurs », qui associent d'autres divinités à Dieu."},
{id:"idolatrie", t:"Idolâtrie", c:"gen", m:["idolâtrie","idoles"], d:"Culte rendu à des statues ou images de dieux, condamné par les trois monothéismes."},
{id:"prophete", t:"Prophète", c:"gen", m:["prophète","prophètes","prophétesse","prophétie","prophétisme"], cs:true, n:"prophetes", d:"Personne qui parle au nom de Dieu. Pour le judaïsme, la prophétie s'achève avec Malachie (Ve s. av. J.-C.) ; pour l'islam, Mahomet est le « sceau des prophètes », le dernier d'une longue lignée qui inclut Adam, Noé, Abraham, Moïse et Jésus. Avec une majuscule, « le Prophète » désigne Mahomet."},
{id:"messie", t:"Messie · Christ", c:"gen", m:["Messie","messie","messies","messianique","messianiques","messianisme","Christ"], cs:true, d:"De l'hébreu mashiaḥ, « oint », traduit en grec par Christos. Roi-sauveur descendant de David attendu par le judaïsme ; Jésus pour les chrétiens, qui l'appellent « le Christ » ; le Coran donne aussi à Jésus le titre de Messie (al-Masīḥ), sans le diviniser."},
{id:"oint", t:"Oint · onction", c:"gen", m:["oint","oints","onction"], cs:true, d:"Consacré par de l'huile versée sur la tête : c'est ainsi qu'étaient investis les rois et les grands prêtres d'Israël. C'est le sens littéral de « messie » et de « christ »."},
{id:"alliance", t:"Alliance", c:"gen", m:["alliance","Alliance","alliance nouvelle"], cs:true, d:"Pacte entre Dieu et les hommes : avec Noé (l'arc-en-ciel), avec Abraham (la circoncision), avec Israël au Sinaï (la Loi). Jérémie annonce une « alliance nouvelle » : « Nouveau Testament » signifie « nouvelle alliance ». L'Arche d'alliance est le coffre qui contenait les tables de la Loi."},
{id:"circoncision", t:"Circoncision", c:"gen", m:["circoncision","circoncis"], d:"Ablation rituelle du prépuce : signe de l'alliance d'Abraham dans le judaïsme (Gn 17), largement pratiquée en islam. Le concile de Jérusalem (~49) en dispense les chrétiens d'origine païenne."},
{id:"schisme", t:"Schisme", c:"gen", m:["schisme","schismes","scission"], d:"Rupture de communion : une partie des fidèles cesse de reconnaître l'autorité de l'autre (Rome et Constantinople en 1054). Il se distingue de l'hérésie, qui porte sur la doctrine ; dans l'arbre, un trait barré signale une rupture."},
{id:"heresie", t:"Hérésie", c:"gen", m:["hérésie","hérésies","hérétique","hérétiques"], d:"Doctrine jugée contraire à la foi par une autorité religieuse (du grec hairesis, « choix »). Le mot dépend du point de vue : chaque camp a pu traiter l'autre d'hérétique."},
{id:"exegese", t:"Exégèse", c:"gen", m:["exégèse","exégètes","exégète"], d:"Interprétation savante des textes sacrés. L'exégèse coranique s'appelle tafsīr ; l'exégèse rabbinique, midrash."},
{id:"canon", t:"Canon des Écritures", c:"gen", m:["canon","canonique","canoniques"], cs:true, d:"Liste officielle des livres reconnus comme Écriture sainte. Les canons juif, catholique, orthodoxe et protestant ne sont pas identiques (les livres des Maccabées, par exemple, n'appartiennent pas à la Bible hébraïque)."},
{id:"mystique", t:"Mystique", c:"gen", m:["mystique","mystiques"], d:"Recherche d'une union directe et intérieure avec Dieu : kabbale juive, mystique chrétienne, soufisme musulman."},
{id:"esoterique", t:"Ésotérique", c:"gen", m:["ésotérique","ésotériques","ésotérisme"], d:"Réservé aux initiés : enseignement d'un sens caché derrière le sens apparent des textes (en arabe bāṭin)."},
{id:"ascese", t:"Ascèse", c:"gen", m:["ascèse","ascète","ascètes","ascétisme"], d:"Discipline de privations (jeûne, pauvreté, solitude, veilles) pour se rapprocher de Dieu."},
{id:"dualisme", t:"Dualisme", c:"gen", m:["dualisme","dualistes","dualiste"], d:"Croyance en deux principes opposés et presque égaux, le Bien et le Mal ou la Lumière et les Ténèbres : manichéisme, cathares."},
{id:"gnose", t:"Gnose · gnostiques", c:"gen", m:["gnostiques","gnostique"], n:"gnose", d:"Courants des premiers siècles pour qui le salut vient d'une connaissance (gnôsis) secrète. Le monde matériel y est l'œuvre d'un dieu inférieur, le démiurge, distinct du vrai Dieu."},
{id:"demiurge", t:"Démiurge", c:"gen", m:["démiurge"], d:"« Artisan » du monde : chez les gnostiques, dieu inférieur, souvent mauvais, qui a façonné la matière."},
{id:"eponyme", t:"Éponyme", c:"gen", m:["éponyme","éponymes"], d:"Qui donne son nom. L'ancêtre éponyme est le personnage, souvent légendaire, dont un peuple, une tribu ou une dynastie tire son nom : Israël, Édom, Moab, Quraysh, Umayya (les Omeyyades)… Ces généalogies disent surtout les liens que les peuples se reconnaissaient."},
{id:"genealogistes", t:"Généalogistes", c:"gen", m:["généalogistes","généalogiste"], d:"Savants qui établissent les lignées. En Arabie, la science des généalogies (nasab) fondait l'identité tribale ; ses listes anciennes divergent souvent."},
{id:"martyr", t:"Martyr", c:"gen", m:["martyrs","martyr","martyre","martyrisé","martyrisés","martyrisée"], d:"Du grec « témoin » : personne mise à mort pour sa foi. Les chiites appellent al-Ḥusayn « le prince des martyrs »."},
{id:"patriarche", t:"Patriarche", c:"gen", m:["patriarche","patriarches","Patriarches","patriarcat","patriarcats"], d:"Trois sens : 1) Abraham, Isaac et Jacob, ancêtres d'Israël (« les Patriarches ») ; 2) titre des évêques des grands sièges chrétiens (Constantinople, Alexandrie, Antioche, Jérusalem, Moscou…) ; 3) chef officiel des Juifs de Palestine romaine, de la famille de Hillel, jusqu'au Ve s."},
{id:"apostasie", t:"Apostasie", c:"gen", m:["apostat","apostats","apostasie"], d:"Abandon de sa religion. Le droit islamique classique la punit sévèrement ; la Ridda (632-633) fut vue comme l'apostasie des tribus arabes après la mort de Mahomet."},
{id:"excommunication", t:"Excommunication", c:"gen", m:["excommunié","excommuniés","excommunications","excommunication"], d:"Exclusion d'un fidèle ou d'un groupe de la communion de son Église. Dans le judaïsme, le ḥérem rabbinique joue un rôle comparable."},
{id:"oecumenique", t:"Œcuménique · œcuménisme", c:"gen", m:["œcuménique","œcuménisme"], d:"Du grec oikoumenê, « la terre habitée ». Un concile œcuménique réunit les évêques de toute l'Église ; l'œcuménisme (XXe s.) cherche à rapprocher les Églises séparées. Le patriarche « œcuménique » est celui de Constantinople."},
{id:"dogme", t:"Dogme", c:"gen", m:["dogme","dogmes"], d:"Vérité de foi définie officiellement par une autorité religieuse et imposée aux fidèles (la Trinité, l'Immaculée Conception, le Coran créé sous la Miḥna…)."},
{id:"diaspora", t:"Diaspora", c:"gen", m:["diaspora"], n:"diaspora", d:"Du grec « dispersion » : communautés vivant hors de leur terre d'origine. La diaspora juive commence avec l'Exil à Babylone (VIe s. av. J.-C.)."},
{id:"semites", t:"Sémites · sémitique", c:"gen", m:["Sémites","sémitique","sémitiques"], cs:true, n:"sem", d:"Mot forgé en 1781 à partir de Sem, fils de Noé, pour une famille de langues : hébreu, araméen, arabe, akkadien, éthiopien… Il désigne des langues, pas une « race »."},
{id:"yhwh", t:"YHWH", c:"gen", m:["YHWH","YHW"], cs:true, d:"Le nom propre du Dieu d'Israël, écrit avec quatre consonnes (le « tétragramme »). Par respect, les juifs ne le prononcent pas et disent Adonaï, « le Seigneur » ; la prononciation « Yahvé » est une reconstruction savante."},
{id:"hebreux", t:"Hébreux · hébreu", c:"gen", m:["Hébreux","hébreu"], cs:true, n:"eber", d:"Nom ancien des Israélites (ʿIvrim), rattaché par la Bible à Éber. L'hébreu, leur langue, est une variante du cananéen ; il est redevenu langue parlée avec le sionisme."},
{id:"arameen", t:"Araméens · araméen", c:"gen", m:["araméen","Araméen","Araméens","araméenne","araméennes","araméens"], cs:true, n:"semites", d:"Peuple de la Syrie ancienne. Sa langue, l'araméen, devient la langue commune du Proche-Orient sous les Perses : c'est celle de Jésus, d'une partie du Talmud et du livre de Daniel ; le syriaque des Églises d'Orient en dérive."},
{id:"ancientestament", t:"Ancien Testament · Bible hébraïque", c:"gen", m:["Ancien Testament","Bible hébraïque"], d:"Nom chrétien des Écritures juives, que les juifs appellent Tanakh : Torah (Loi), Neviim (Prophètes), Ketouvim (Écrits). Les Bibles catholique et orthodoxe y ajoutent quelques livres grecs (Maccabées, Sagesse…)."},
{id:"nouveautestament", t:"Nouveau Testament", c:"chr", m:["Nouveau Testament"], d:"Seconde partie de la Bible chrétienne : 27 livres écrits en grec entre 50 et 120 environ — quatre évangiles, Actes des Apôtres, épîtres, Apocalypse. « Testament » traduit « alliance »."},

/* judaïsme */
{id:"torah", t:"Torah", c:"jud", m:["Torah"], cs:true, n:"sinai", d:"« Enseignement, loi ». Au sens strict : les cinq premiers livres de la Bible (Genèse, Exode, Lévitique, Nombres, Deutéronome), attribués à Moïse ; au sens large, tout l'enseignement juif. Les historiens datent sa rédaction des VIIe–Ve s. av. J.-C."},
{id:"torahorale", t:"Torah orale", c:"jud", m:["Torah orale"], cs:true, n:"sinai", d:"Tradition d'interprétation de la Loi que les rabbins font remonter à Moïse au Sinaï, transmise de maître à disciple, puis mise par écrit dans la Michna (vers 200) et le Talmud. Les sadducéens puis les karaïtes la rejettent."},
{id:"pentateuque", t:"Pentateuque", c:"jud", m:["Pentateuque"], d:"Nom grec (« cinq livres ») de la Torah : Genèse, Exode, Lévitique, Nombres, Deutéronome. Les Samaritains en ont leur propre version."},
{id:"michna", t:"Michna", c:"jud", m:["Michna"], cs:true, n:"michna", d:"Premier code écrit de la Torah orale, compilé vers 200 par Juda ha-Nassi : six « ordres » (agriculture, fêtes, femmes, dommages, choses saintes, pureté), divisés en traités."},
{id:"talmud", t:"Talmud", c:"jud", m:["Talmud","Talmuds"], cs:true, n:"talmudb", d:"La Michna accompagnée de son immense commentaire, la Guemara. Il en existe deux : le Talmud de Jérusalem (~400) et le Talmud de Babylone (~500-600), qui fait autorité. On le cite par traité, feuillet et face : « Shabbat 31a »."},
{id:"midrash", t:"Midrash", c:"jud", m:["Midrash","midrash"], cs:true, d:"Commentaire rabbinique de la Bible, qui en comble les silences par des récits et des enseignements (Genèse Rabba, Ve s.). C'est la source de nombreuses légendes reprises aussi par la tradition musulmane."},
{id:"halakha", t:"Halakha", c:"jud", m:["halakha"], d:"La loi juive, la « marche » à suivre au quotidien — par opposition à l'aggada, la partie narrative et morale du Talmud."},
{id:"aggada", t:"Aggada", c:"jud", m:["aggada"], d:"Partie narrative du Talmud et du Midrash : récits, légendes, sagesse — par opposition à la halakha, la loi."},
{id:"rabbin", t:"Rabbin · judaïsme rabbinique", c:"jud", m:["rabbins","rabbin","rabbinique","rabbiniques","rabbanites"], n:"yohanan", d:"« Mon maître ». Héritiers des pharisiens, les rabbins font du judaïsme, après la destruction du Temple en 70, une religion de l'étude et de la prière, sans sacrifices. Les « rabbanites » sont les partisans de la Torah orale, face aux karaïtes."},
{id:"sanhedrin", t:"Sanhédrin", c:"jud", m:["Sanhédrin"], cs:true, d:"Conseil et tribunal suprême du judaïsme à l'époque romaine (71 membres selon la Michna), présidé par le grand prêtre ou, selon la tradition rabbinique, par les grands maîtres (les Paires, puis la famille de Hillel)."},
{id:"grandpretre", t:"Grand prêtre", c:"jud", m:["grand prêtre","Grand prêtre","grands prêtres","grand sacerdoce"], cs:true, d:"Chef du sacerdoce du Temple de Jérusalem, seul autorisé à entrer, une fois l'an (Kippour), dans le Saint des saints. Fonction héréditaire chez les descendants d'Aaron, puis nommée par les rois hasmonéens, Hérode et les Romains."},
{id:"kohanim", t:"Kohanim et lévites", c:"jud", m:["kohanim","lévites"], cs:true, n:"levi", d:"Kohanim : prêtres juifs, descendants d'Aaron (le nom Cohen en vient). Lévites : autres membres de la tribu de Lévi, chargés du chant et du service du Temple."},
{id:"temple", t:"Temple de Jérusalem", c:"jud", m:["Temple","Premier Temple","Second Temple"], cs:true, d:"Sanctuaire unique du culte de YHWH. Le Premier Temple, attribué à Salomon, est détruit par Babylone en 587/586 av. J.-C. ; le Second, dédié en 515 et agrandi par Hérode, est détruit par les Romains en 70. Le Mur occidental est un vestige de son esplanade."},
{id:"saintdessaints", t:"Saint des saints", c:"jud", m:["Saint des saints"], cs:true, d:"Salle la plus sacrée du Temple, où se trouvait l'Arche d'alliance ; seul le grand prêtre y entrait, une fois par an."},
{id:"montdutemple", t:"Mont du Temple · Esplanade des Mosquées", c:"jud", m:["Mont du Temple","Esplanade des Mosquées"], cs:true, d:"Colline de Jérusalem où s'élevaient les deux Temples ; depuis la fin du VIIe s., le Dôme du Rocher et la mosquée al-Aqṣā. Lieu le plus saint du judaïsme et troisième lieu saint de l'islam, au cœur du conflit israélo-palestinien."},
{id:"synagogue", t:"Synagogue", c:"jud", m:["synagogue","synagogues"], d:"« Assemblée » : lieu juif de prière, de lecture et d'étude, sans sacrifices. Née sans doute pendant l'Exil, elle prend le relais du Temple après 70."},
{id:"shema", t:"Shema", c:"jud", m:["Shema"], cs:true, d:"« Écoute, Israël : YHWH est notre Dieu, YHWH est un » (Dt 6,4) : profession de foi juive, récitée matin et soir et à l'heure de la mort."},
{id:"paque", t:"Pâque juive (Pessah)", c:"jud", m:["Pâque"], cs:true, d:"Fête du printemps qui commémore la sortie d'Égypte. Jésus est crucifié au moment de la Pâque ; la fête chrétienne de Pâques célèbre sa résurrection."},
{id:"pourim", t:"Pourim", c:"jud", m:["Pourim"], cs:true, n:"esther", d:"Fête joyeuse qui commémore le salut des Juifs de Perse raconté par le livre d'Esther."},
{id:"hanoucca", t:"Hanoucca", c:"jud", m:["Hanoucca"], cs:true, n:"judasmacc", d:"Fête des Lumières (huit jours) qui commémore la purification du Temple par les Maccabées en 164 av. J.-C."},
{id:"exilarque", t:"Exilarque", c:"jud", m:["exilarque","exilarques"], n:"exilarques", d:"Resh Galouta, « chef de l'exil » : chef officiel des Juifs de Babylonie, reconnu par les rois perses puis par les califes, qui se réclamait de la lignée de David."},
{id:"gaon", t:"Gaon · Gueonim", c:"jud", m:["gaon","Gueonim","gueonim"], n:"gueonim", d:"« Excellence » : titre des chefs des académies talmudiques de Babylonie (VIe–XIe s.), dont les avis faisaient autorité dans tout le monde juif. Plus tard, titre d'honneur d'un très grand savant (le Gaon de Vilna)."},
{id:"responsa", t:"Responsa", c:"jud", m:["responsa"], d:"Réponses écrites d'un rabbin à des questions de loi envoyées par des communautés parfois lointaines ; genre né chez les Gueonim et toujours pratiqué."},
{id:"yeshiva", t:"Yeshiva", c:"jud", m:["yeshiva","yeshivot"], d:"École d'étude du Talmud."},
{id:"tsaddik", t:"Tsaddik (rabbi)", c:"jud", m:["tsaddik"], d:"« Juste » : maître charismatique d'une communauté hassidique, appelé aussi rabbi ou rebbe, souvent à la tête d'une dynastie."},
{id:"mitnagdim", t:"Mitnagdim", c:"jud", m:["mitnagdim"], n:"vilna", d:"« Opposants » : juifs lituaniens qui combattent le hassidisme au nom de l'étude talmudique, autour du Gaon de Vilna."},
{id:"sefirot", t:"Sefirot", c:"jud", m:["sefirot"], n:"kabbale", d:"Dans la kabbale, les dix émanations ou attributs par lesquels Dieu, infini et caché, se manifeste et crée le monde."},
{id:"kabbale", t:"Kabbale", c:"jud", m:["kabbale","kabbaliste","kabbalistes"], n:"kabbale", d:"« Réception » : mystique juive qui spécule sur les noms divins et les sefirot ; elle apparaît en Provence et en Espagne aux XIIe–XIIIe s. (Zohar) et se renouvelle à Safed au XVIe s."},
{id:"zohar", t:"Zohar", c:"jud", m:["Zohar"], cs:true, n:"kabbale", d:"« Livre de la Splendeur » : commentaire mystique de la Torah en araméen, composé en Castille vers 1280-1290 par Moïse de León, qui l'attribua au maître du IIe s. Siméon bar Yohaï."},
{id:"septante", t:"Septante", c:"jud", m:["Septante"], cs:true, n:"alexandrie", d:"Traduction grecque de la Bible hébraïque faite à Alexandrie (IIIe–IIe s. av. J.-C.), selon la légende par 70 (ou 72) traducteurs. C'est la Bible des premiers chrétiens."},
{id:"massoretique", t:"Texte massorétique", c:"jud", m:["massorétique"], d:"Texte hébreu de la Bible fixé, avec ses voyelles, par les Massorètes (VIIe–Xe s.) : c'est la base des Bibles actuelles. Ses âges et ses dates diffèrent parfois de ceux de la Septante."},
{id:"hasmoneens", t:"Hasmonéens", c:"jud", m:["Hasmonéens","Hasmonéen","hasmonéen","hasmonéenne","hasmonéens"], cs:true, n:"mattathias", d:"Dynastie de prêtres-rois issue des Maccabées, qui gouverne une Judée indépendante de 142 à 63 av. J.-C., puis sous tutelle romaine jusqu'en 37 av. J.-C."},
{id:"maccabees", t:"Maccabées", c:"jud", m:["Maccabées"], cs:true, n:"judasmacc", d:"Surnom (« le marteau ») de Judas, puis de sa famille, qui mène la révolte juive contre les Séleucides (167-164 av. J.-C.). Leurs descendants forment la dynastie hasmonéenne."},
{id:"seleucides", t:"Séleucides", c:"his", m:["Séleucides","séleucide"], cs:true, d:"Dynastie grecque fondée par Séleucos, général d'Alexandre le Grand, qui règne sur la Syrie et la Mésopotamie (312–63 av. J.-C.). Antiochos IV provoque la révolte des Maccabées."},
{id:"herem", t:"Ḥérem", c:"jud", m:["ḥérem"], d:"« Consécration à la destruction » : dans la guerre sainte biblique, ennemis et butin voués à Dieu sont anéantis. Plus tard, le mot désigne l'excommunication rabbinique."},
{id:"aqeda", t:"Aqéda", c:"jud", m:["Aqéda"], cs:true, n:"isaac", d:"« Ligature » : le sacrifice d'Isaac interrompu par un ange (Gn 22). Les chrétiens y voient une préfiguration de la Passion ; dans l'islam, la majorité des exégètes rapporte l'épisode à Ismaël."},
{id:"levirat", t:"Lévirat", c:"jud", m:["lévirat"], d:"Coutume biblique (Dt 25) : le frère d'un homme mort sans enfant épouse la veuve, et le premier fils porte le nom du défunt."},
{id:"noachides", t:"Lois noachides", c:"jud", m:["lois noachides"], n:"noe", d:"Sept commandements que le Talmud fait remonter à Noé et qui valent pour tous les non-juifs : ne pas idolâtrer, ne pas blasphémer, ne pas tuer, ne pas voler, éviter l'inceste et l'adultère, ne pas manger la chair d'un animal vivant, établir des tribunaux."},
{id:"yetser", t:"Yetser ha-raʿ", c:"jud", m:["yetser ha-raʿ"], d:"« Penchant au mal » : dans la pensée rabbinique, tendance que tout homme porte en lui, à côté du penchant au bien, et qu'il peut maîtriser — d'où le refus de l'idée chrétienne de péché originel."},
{id:"conversos", t:"Conversos (marranes)", c:"jud", m:["conversos","marranes"], n:"sefarades", d:"Juifs d'Espagne et du Portugal convertis au catholicisme, souvent par la force (1391, 1492, 1497). Soupçonnés de judaïser en secret (d'où l'insulte « marranes »), ils sont la principale cible de l'Inquisition espagnole."},
{id:"pogrom", t:"Pogrom", c:"jud", m:["pogroms","pogrom"], d:"Mot russe : émeute meurtrière contre une communauté juive, souvent tolérée ou encouragée par les autorités (Empire russe, 1881-1906)."},
{id:"antijudaisme", t:"Antijudaïsme · antisémitisme", c:"jud", m:["antijudaïsme","antisémitisme","antisémite"], d:"L'antijudaïsme est une hostilité religieuse, d'origine surtout chrétienne (accusations de « déicide », de crime rituel). L'antisémitisme, mot de 1879, est une haine raciale et politique ; le nazisme l'a poussé jusqu'au génocide."},
{id:"nakba", t:"Nakba", c:"isl", m:["Nakba"], cs:true, n:"israel1948", d:"« Catastrophe » en arabe : exode et expulsion d'environ 700 000 Palestiniens pendant la guerre de 1948."},
{id:"sionisme", t:"Sionisme", c:"jud", m:["sionisme","sioniste","antisionisme"], n:"sionisme", d:"Mouvement national juif né à la fin du XIXe s. (Herzl, 1897) pour un retour et un État juif en Terre d'Israël — Sion est l'un des noms de Jérusalem."},
{id:"hassidisme", t:"Hassidisme", c:"jud", m:["hassidisme","hassidique","hassidiques","hassidim"], n:"hassidisme", d:"Mouvement de piété populaire, joyeuse et fervente, fondé en Podolie par le Baal Shem Tov vers 1740 et organisé autour de maîtres charismatiques (tsaddikim)."},
{id:"haredim", t:"Haredim (ultra-orthodoxes)", c:"jud", m:["haredim","ultra-orthodoxes"], n:"haredim", d:"« Ceux qui tremblent » (devant Dieu) : juifs ultra-orthodoxes qui refusent la modernité laïque et vivent selon une stricte observance de la loi."},
{id:"haskala", t:"Haskala", c:"jud", m:["Haskala"], cs:true, n:"haskala", d:"Les « Lumières » juives (fin XVIIIe–XIXe s.) : ouverture à la culture européenne, aux langues et aux sciences, autour de Moses Mendelssohn."},
{id:"karaisme", t:"Karaïsme", c:"jud", m:["karaïtes","karaïte","karaïsme"], n:"karaisme", d:"Courant juif né vers 760 qui rejette la Torah orale et le Talmud : seule l'Écriture fait loi."},
{id:"pharisiens", t:"Pharisiens", c:"jud", m:["pharisiens","pharisien"], n:"pharisiens", d:"Courant juif de l'époque du Second Temple (« les séparés ») : Torah orale, résurrection des morts, pureté dans la vie quotidienne. Ce sont les ancêtres des rabbins."},
{id:"sadduceens", t:"Sadducéens", c:"jud", m:["sadducéens","sadducéen"], n:"sadduceens", d:"Parti des grandes familles sacerdotales : seule la Torah écrite fait loi, pas de résurrection. Il disparaît avec le Temple en 70."},
{id:"esseniens", t:"Esséniens", c:"jud", m:["Esséniens","esséniens"], cs:true, n:"esseniens", d:"Communauté juive ascétique et apocalyptique (IIe s. av. – Ier s. apr. J.-C.), que la plupart des historiens relient aux manuscrits de la mer Morte trouvés à Qumrân."},
{id:"zelotes", t:"Zélotes", c:"jud", m:["Zélotes","zélotes","Sicaires","sicaires"], cs:true, n:"zelotes", d:"Juifs radicaux qui refusent toute domination étrangère (« pas d'autre maître que Dieu ») et mènent la révolte contre Rome (66-73) ; les Sicaires sont leur aile la plus violente."},
{id:"samaritains", t:"Samaritains", c:"jud", m:["Samaritains","samaritaine","samaritain"], cs:true, n:"samaritains", d:"Descendants des Israélites du Nord, qui ont leur propre Pentateuque et pour lieu saint le mont Garizim. Moins d'un millier aujourd'hui."},
{id:"exil", t:"Exil à Babylone", c:"jud", m:["Exil"], cs:true, n:"exil", d:"Déportation des élites de Juda à Babylone par Nabuchodonosor (597 et 587/586 av. J.-C.), jusqu'à l'édit de Cyrus (538). Période décisive pour l'écriture de la Bible et la naissance du monothéisme strict."},
{id:"exode", t:"Exode", c:"jud", m:["Exode"], cs:true, n:"moise", d:"Sortie d'Égypte des Hébreux conduits par Moïse, récit fondateur d'Israël (livre de l'Exode). Aucune trace archéologique n'atteste un départ massif : les historiens y voient une mémoire reconstruite."},
{id:"grandeassemblee", t:"Grande Assemblée", c:"jud", m:["Grande Assemblée"], cs:true, n:"grandeassemblee", d:"Institution de 120 sages que la tradition situe après l'Exil, autour d'Esdras ; elle aurait fixé les prières et le canon biblique. Son existence est débattue."},
{id:"amoraim", t:"Tannaïm · Amoraïm", c:"jud", m:["Amoraïm","Tannaïm"], cs:true, n:"michna", d:"Tannaïm : maîtres de la Michna (Ier–IIe s.). Amoraïm : maîtres qui la commentent dans les académies de Galilée et de Babylonie (IIIe–Ve s.) ; leurs débats forment le Talmud."},
{id:"rishonim", t:"Rishonim · Aharonim", c:"jud", m:["Rishonim","Aharonim"], cs:true, n:"rishonim", d:"Rishonim, « premiers » : commentateurs et codificateurs du Talmud du XIe au XVe s. (Rachi, Maïmonide). Aharonim, « derniers » : leurs successeurs, depuis le Choulhan aroukh (1565)."},
{id:"tossafistes", t:"Tossafistes", c:"jud", m:["tossafistes"], n:"rachi", d:"Commentateurs du Talmud des XIIe–XIIIe s. en France et en Allemagne, descendants et disciples de Rachi ; leurs gloses (tossafot) sont imprimées en face des siennes."},
{id:"shoah", t:"Shoah", c:"jud", m:["Shoah"], cs:true, n:"shoah", d:"« Catastrophe » en hébreu : extermination d'environ six millions de Juifs d'Europe par l'Allemagne nazie et ses complices (1941-1945)."},
{id:"deuteronomiste", t:"Deutéronomiste", c:"jud", m:["deutéronomiste"], n:"josias", d:"Relatif au Deutéronome : courant de scribes de la fin de la monarchie de Juda (VIIe s. av. J.-C.) qui exige un culte unique à Jérusalem et relit l'histoire d'Israël, de Josué aux Rois, selon sa fidélité à YHWH."},
{id:"cananeens", t:"Cananéens", c:"his", m:["Cananéens","cananéenne","cananéen","cananéennes"], cs:true, n:"canaan", d:"Peuples du Levant (Canaan) aux âges du bronze et du fer, dont la langue et la culture sont très proches de celles des premiers Israélites ; les Phéniciens en sont les héritiers."},

/* christianisme */
{id:"evangile", t:"Évangile", c:"chr", m:["évangiles","évangile","Évangile"], d:"« Bonne nouvelle » : l'annonce du salut par Jésus. Désigne aussi les quatre récits de sa vie reconnus par les Églises (Marc ~70, Matthieu et Luc ~80-90, Jean ~90-100) et d'autres, dits apocryphes (Évangile de Thomas). Le Coran parle de l'Injīl donné à Jésus."},
{id:"apotre", t:"Apôtre", c:"chr", m:["apôtres","apôtre"], n:"douze", d:"« Envoyé » : les Douze choisis par Jésus, ainsi que Paul. Les évêques se disent leurs successeurs (« succession apostolique »)."},
{id:"epitre", t:"Épître", c:"chr", m:["épître","épîtres"], d:"Lettre du Nouveau Testament, attribuée à Paul, Pierre, Jean, Jacques ou Jude."},
{id:"peres", t:"Pères de l'Église", c:"chr", m:["Pères latins","Pères de l'Église","Pères grecs"], cs:true, d:"Écrivains chrétiens des premiers siècles dont l'autorité fait référence : Irénée, Athanase, Augustin, Jérôme, Jean Damascène…"},
{id:"concile", t:"Concile", c:"chr", m:["concile","conciles"], d:"Assemblée d'évêques qui fixe la doctrine et la discipline. Sept conciles « œcuméniques », de Nicée I (325) à Nicée II (787), sont reconnus par catholiques et orthodoxes."},
{id:"trinite", t:"Trinité", c:"chr", m:["Trinité","trinitaire"], cs:true, d:"Dogme chrétien : un seul Dieu en trois personnes, Père, Fils et Saint-Esprit, défini aux conciles de Nicée (325) et de Constantinople (381). Juifs et musulmans y voient une atteinte à l'unicité de Dieu (Coran 4,171)."},
{id:"antitrinitaire", t:"Antitrinitaire", c:"chr", m:["antitrinitaire","antitrinitaires","antitrinitarisme"], d:"Qui rejette la Trinité tout en se disant chrétien : Arius, Michel Servet, unitariens, Témoins de Jéhovah."},
{id:"consubstantiel", t:"Consubstantiel (homoousios)", c:"chr", m:["consubstantiel","homoousios"], n:"nicee", d:"« De même substance » : formule du concile de Nicée (325), selon laquelle le Fils est Dieu au même titre que le Père, contre Arius."},
{id:"theotokos", t:"Theotokos", c:"chr", m:["Theotokos"], cs:true, n:"ephese", d:"« Mère de Dieu » : titre de Marie défendu au concile d'Éphèse (431) contre Nestorius, qui préférait « Mère du Christ »."},
{id:"christologie", t:"Christologie", c:"chr", m:["christologie","christologique","christologiques"], d:"Doctrine sur la personne du Christ : comment il est à la fois Dieu et homme. Les querelles christologiques du Ve s. ont séparé l'Église de l'Orient, les Églises orthodoxes orientales et l'Église impériale."},
{id:"miaphysite", t:"Miaphysites", c:"chr", m:["miaphysites","miaphysite","monophysites"], n:"orientaux", d:"Chrétiens qui confessent dans le Christ « une seule nature, à la fois divine et humaine » et rejettent la formule du concile de Chalcédoine (451) : Églises copte, syriaque, arménienne, éthiopienne."},
{id:"nestorien", t:"Nestorien", c:"chr", m:["nestorienne","nestorien","nestoriens"], n:"egliseorient", d:"Qualificatif donné, à tort selon les historiens, à l'Église de l'Orient, accusée de suivre Nestorius, qui distinguait fortement en Jésus la divinité et l'humanité."},
{id:"chalcedonien", t:"Chalcédonien", c:"chr", m:["chalcédonienne","chalcédonien","chalcédoniens"], n:"chalcedoine", d:"Qui accepte la définition du concile de Chalcédoine (451) : le Christ est une seule personne en deux natures. Catholiques, orthodoxes et protestants sont chalcédoniens."},
{id:"credo", t:"Credo", c:"chr", m:["Credo"], cs:true, d:"« Je crois » : résumé officiel de la foi chrétienne. Le Credo de Nicée-Constantinople (325-381) est commun aux grandes Églises, à la différence près du Filioque."},
{id:"filioque", t:"Filioque", c:"chr", m:["Filioque"], cs:true, n:"schisme1054", d:"« Et du Fils » : mots ajoutés par les Latins au Credo (l'Esprit procède du Père « et du Fils »), rejetés par les orthodoxes ; l'un des motifs du schisme de 1054."},
{id:"azyme", t:"Pain azyme", c:"chr", m:["azyme"], d:"Pain sans levain, utilisé par les Latins pour l'eucharistie, comme à la Pâque juive ; les Grecs utilisent du pain levé — motif de querelle en 1054."},
{id:"primaute", t:"Primauté pontificale", c:"chr", m:["primauté"], d:"Autorité suprême revendiquée par l'évêque de Rome, le pape, sur toute l'Église, en tant que successeur de Pierre. Les orthodoxes ne lui reconnaissent qu'une primauté d'honneur."},
{id:"pape", t:"Pape", c:"chr", m:["pape","papes","pontificale","pontifical","pontificaux","papauté"], n:"catholicisme", d:"Évêque de Rome, chef de l'Église catholique, considéré comme le successeur de l'apôtre Pierre."},
{id:"eveque", t:"Évêque", c:"chr", m:["évêque","évêques","épiscopat"], d:"« Surveillant » : responsable d'une Église locale (diocèse), successeur des apôtres pour les catholiques, les orthodoxes et les anglicans."},
{id:"pentarchie", t:"Pentarchie", c:"chr", m:["pentarchie"], n:"chalcedoniens", d:"Gouvernement de l'Église impériale par cinq patriarcats : Rome, Constantinople, Alexandrie, Antioche et Jérusalem."},
{id:"autocephale", t:"Autocéphale", c:"chr", m:["autocéphales","autocéphale","autocéphalie"], n:"orthodoxie", d:"« Qui a sa propre tête » : Église orthodoxe indépendante, qui élit son chef elle-même, tout en restant en communion avec les autres."},
{id:"sacrement", t:"Sacrement", c:"chr", m:["sacrements","sacrement"], d:"Rite par lequel Dieu donne sa grâce : sept pour les catholiques et les orthodoxes (baptême, eucharistie, mariage…), deux pour la plupart des protestants (baptême et Cène)."},
{id:"cene", t:"Cène · eucharistie", c:"chr", m:["Cène","eucharistie"], cs:true, d:"Le dernier repas de Jésus et le rite qui le commémore (messe, eucharistie, sainte Cène). La façon dont le Christ y est présent divise catholiques, luthériens et réformés."},
{id:"indulgences", t:"Indulgences", c:"chr", m:["indulgences","indulgence"], n:"reforme1517", d:"Remise, accordée par l'Église, des peines dues au péché ; leur vente pour financer Saint-Pierre de Rome provoque la protestation de Luther en 1517."},
{id:"predestination", t:"Prédestination", c:"chr", m:["prédestination"], d:"Doctrine selon laquelle Dieu a choisi de toute éternité ceux qui seront sauvés (Augustin, Calvin)."},
{id:"sacerdoce", t:"Sacerdoce universel", c:"chr", m:["sacerdoce universel"], d:"Principe de la Réforme : tous les baptisés sont prêtres ; les pasteurs ne forment pas un clergé doté de pouvoirs sacramentels propres."},
{id:"pecheoriginel", t:"Péché originel", c:"chr", m:["péché originel"], n:"adam", d:"Doctrine chrétienne (Paul, Augustin) : la faute d'Adam et Ève se transmet à toute l'humanité, que le Christ vient sauver. Le judaïsme et l'islam la rejettent."},
{id:"reveils", t:"Grands Réveils", c:"chr", m:["Grands Réveils","Réveils"], cs:true, d:"Vagues de ferveur protestante aux États-Unis (XVIIIe–XIXe s.) : prédication émotive, conversion personnelle ; elles donnent naissance à de nombreuses Églises nouvelles."},
{id:"charismatiques", t:"Charismatiques", c:"chr", m:["charismatiques"], d:"Chrétiens (catholiques ou protestants) qui, comme les pentecôtistes, insistent sur les dons de l'Esprit : parler en langues, guérisons, prophéties."},
{id:"deicide", t:"Déicide", c:"chr", m:["déicide"], n:"vatican2", d:"« Meurtre de Dieu » : accusation portée pendant des siècles contre les Juifs pour la mort de Jésus, rejetée par l'Église catholique en 1965 (Nostra Aetate)."},
{id:"infaillibilite", t:"Infaillibilité", c:"chr", m:["infaillibilité","infaillible","infaillibles"], d:"Pour les catholiques (Vatican I, 1870), le pape ne peut se tromper quand il définit solennellement un point de foi ou de morale. Pour les chiites, les imams sont eux aussi infaillibles et sans péché (maʿṣūm)."},
{id:"scolastique", t:"Scolastique", c:"chr", m:["scolastique"], d:"Méthode des universités médiévales (XIIe–XVe s.) qui cherche à accorder la foi et la raison d'Aristote ; Thomas d'Aquin en est le maître."},
{id:"icones", t:"Icônes · iconoclasme", c:"chr", m:["icônes","icône","iconoclastes","iconodoules","iconoclasme"], n:"iconoclasme", d:"Les icônes sont des images saintes peintes, vénérées par les chrétiens d'Orient. Les iconoclastes (« briseurs d'images ») les condamnent ; les iconodoules les défendent. La querelle déchire Byzance de 726 à 843."},
{id:"raskol", t:"Raskol", c:"chr", m:["Raskol"], cs:true, n:"vieuxcroyants", d:"« Schisme » en russe : séparation des vieux-croyants après les réformes liturgiques du patriarche Nikon (1666)."},
{id:"nostraaetate", t:"Nostra Aetate", c:"chr", m:["Nostra Aetate"], cs:true, n:"vatican2", d:"« À notre époque » : déclaration du concile Vatican II (28 octobre 1965) sur les religions non chrétiennes. Elle rejette l'accusation de déicide contre les Juifs et exprime l'estime de l'Église pour les musulmans."},
{id:"immaculee", t:"Immaculée Conception", c:"chr", m:["Immaculée Conception"], cs:true, d:"Dogme catholique (1854) : Marie a été préservée du péché originel dès sa conception dans le ventre de sa mère. À ne pas confondre avec la conception virginale de Jésus."},
{id:"assomption", t:"Assomption", c:"chr", m:["Assomption"], cs:true, d:"Dogme catholique (1950) : à la fin de sa vie, Marie a été élevée au ciel avec son corps."},
{id:"conceptionvirginale", t:"Conception virginale", c:"chr", m:["Conception virginale","conception virginale","naissance virginale"], cs:true, n:"jesus", d:"Croyance selon laquelle Jésus est né de Marie sans père humain, affirmée par Matthieu, Luc et le Coran. Dans l'arbre, Jésus est rattaché à Joseph par un trait spécial : filiation légale."},
{id:"apocryphe", t:"Apocryphe", c:"chr", m:["Protévangile de Jacques","apocryphe","apocryphes"], d:"Écrit religieux non retenu dans le canon. Le Protévangile de Jacques (~150), apocryphe sur l'enfance de Marie, est la source des noms de ses parents, Joachim et Anne."},
{id:"huguenots", t:"Huguenots", c:"chr", m:["Huguenots","huguenots"], cs:true, n:"calvin", d:"Surnom des protestants calvinistes français aux XVIe–XVIIe s."},
{id:"jesuites", t:"Jésuites", c:"chr", m:["Jésuites","jésuites"], cs:true, n:"trente", d:"Compagnie de Jésus, ordre fondé par Ignace de Loyola (1540) : enseignement, missions lointaines, fer de lance de la Réforme catholique."},
{id:"croisades", t:"Croisades", c:"chr", m:["croisade","croisades","croisés"], n:"croisades", d:"Pèlerinages armés lancés par la papauté pour prendre ou défendre Jérusalem (1095-1291), puis contre d'autres ennemis de l'Église (païens baltes, cathares)."},
{id:"inquisition", t:"Inquisition", c:"chr", m:["Inquisition"], cs:true, n:"inquisition", d:"Tribunal ecclésiastique chargé de poursuivre l'hérésie (1231). En Espagne (1478), sous contrôle royal, il vise surtout les juifs et les musulmans convertis soupçonnés d'insincérité."},
{id:"morisques", t:"Morisques", c:"isl", m:["morisques"], d:"Musulmans d'Espagne convertis de force au catholicisme (1502-1526), finalement expulsés en 1609-1614."},

/* islam */
{id:"coran", t:"Coran", c:"isl", m:[], auto:false, n:"mushaf", d:"Livre saint de l'islam, parole de Dieu révélée à Mahomet selon les musulmans (610-632) : 114 sourates divisées en versets. Le texte officiel est fixé sous le calife ʿUthmān (~650)."},
{id:"sourate", t:"Sourate", c:"isl", m:["sourate","sourates"], d:"Chapitre du Coran ; il y en a 114, chacune divisée en versets (āya). La référence « 2,127 » se lit : sourate 2, verset 127."},
{id:"hegire", t:"Hégire", c:"isl", m:["hégire"], n:"mahomet", d:"« Émigration » de Mahomet et des premiers musulmans de La Mecque à Médine en 622. Elle marque l'an 1 du calendrier musulman, lunaire (année de 354 jours), instauré par ʿUmar en 638."},
{id:"sira", t:"Sīra", c:"isl", m:["Sīra"], cs:true, d:"Biographie traditionnelle du Prophète. La plus ancienne, celle d'Ibn Isḥāq (~750), n'est connue que par la version d'Ibn Hishām († 833)."},
{id:"hadith", t:"Hadith", c:"isl", m:["hadiths","hadith"], n:"hadith", d:"Récit rapportant une parole ou un acte du Prophète, transmis par une chaîne de garants (isnād). Sunnites et chiites ont leurs propres recueils."},
{id:"isnad", t:"Isnād", c:"isl", m:["isnād"], n:"hadith", d:"Chaîne des transmetteurs d'un hadith (« X m'a rapporté, d'après Y, qui l'a entendu de Z… ») ; pour les savants musulmans, sa solidité fonde l'authenticité du récit."},
{id:"sunna", t:"Sunna", c:"isl", m:["Sunna","sunna"], cs:true, n:"sunnisme", d:"« Tradition » : la conduite exemplaire du Prophète, connue par les hadiths ; deuxième source du droit après le Coran. Les sunnites sont les « gens de la Sunna »."},
{id:"sunnites", t:"Sunnites", c:"isl", m:["sunnites","sunnite","Sunnites"], cs:true, n:"sunnisme", d:"Majorité des musulmans (85-90 %) : ils reconnaissent la légitimité des quatre premiers califes et l'autorité de la Sunna et du consensus des savants."},
{id:"chiites", t:"Chiites", c:"isl", m:["chiites","chiite","Chiites","chiisme"], cs:true, n:"shiatali", d:"Musulmans (10-15 %) pour qui la direction de la communauté revient à ʿAlī et à ses descendants, les imams. Majoritaires en Iran, en Irak, à Bahreïn et en Azerbaïdjan."},
{id:"kharijites", t:"Kharijites", c:"isl", m:["kharijites","kharijite"], n:"kharijites", d:"Ceux qui « sortent » du camp d'ʿAlī en 657 : le pouvoir revient au plus pieux, quelle que soit son origine, et l'auteur d'un péché grave n'est plus musulman."},
{id:"calife", t:"Calife · califat", c:"isl", m:["calife","califes","califat","califats","califal","khalīfa"], n:"rashidun", d:"« Successeur » (khalīfa) du Prophète à la tête de la communauté. Califes « bien guidés » (632-661), puis Omeyyades, Abbassides, Fatimides et Cordouans rivaux, Ottomans ; le califat est aboli en 1924. Le Coran emploie aussi le mot pour Adam, « lieutenant » de Dieu sur terre."},
{id:"imam", t:"Imam · imamat", c:"isl", m:["imam","imams","Imam","imamat"], cs:true, d:"Chez les sunnites, celui qui dirige la prière. Chez les chiites, le guide de la communauté, descendant d'ʿAlī et de Fāṭima, désigné par Dieu et infaillible : douze pour les duodécimains, une autre lignée pour les ismaéliens."},
{id:"mahdi", t:"Mahdī", c:"isl", m:["Mahdī","mahdī"], cs:true, n:"mahdi", d:"« Le bien guidé » : sauveur attendu à la fin des temps pour établir la justice. Pour les chiites duodécimains, c'est le douzième imam, caché depuis 874."},
{id:"occultation", t:"Occultation", c:"isl", m:["occultation","occulté"], n:"mahdi", d:"Ghayba : l'imam ne meurt pas mais se cache, jusqu'à son retour à la fin des temps. L'idée apparaît chez les Kaysānites (VIIe s.) et devient centrale chez les duodécimains (874, puis 941)."},
{id:"ahlalbayt", t:"Ahl al-bayt", c:"isl", m:["ahl al-bayt","Gens de la Maison"], cs:true, n:"fatima", d:"« Les gens de la Maison » : la famille du Prophète — Fāṭima, ʿAlī, al-Ḥasan, al-Ḥusayn et leurs descendants —, objet d'une vénération particulière, surtout chez les chiites."},
{id:"sayyid", t:"Sayyid · chérif", c:"isl", m:["sayyids","sayyid","chérifs","chérif","chérifienne"], cs:true, d:"Titres des descendants du Prophète par al-Ḥasan et al-Ḥusayn (sayyid surtout en Orient, chérif au Maghreb et au Hedjaz). Les familles royales du Maroc et de Jordanie sont chérifiennes."},
{id:"fitna", t:"Fitna", c:"isl", m:["fitna"], n:"fitna1", d:"« Épreuve, discorde » : guerre civile entre musulmans. La première (656-661) fonde la division entre sunnites, chiites et kharijites."},
{id:"ridda", t:"Ridda", c:"isl", m:["Ridda"], cs:true, n:"ridda", d:"« Apostasie » : sécession de tribus arabes à la mort de Mahomet (632), réprimée par Abū Bakr."},
{id:"dhimmi", t:"Dhimmī", c:"isl", m:["dhimmī","dhimmi"], d:"« Protégé » : statut des juifs et des chrétiens (puis des zoroastriens) en terre d'islam. Liberté de culte et protection, contre un impôt particulier (jizya) et des restrictions (pas de nouveaux lieux de culte, signes distinctifs…)."},
{id:"fiqh", t:"Fiqh · charia", c:"isl", m:["fiqh","charia"], d:"« Compréhension » : le droit musulman, élaboré par les juristes à partir du Coran, de la Sunna, du consensus et du raisonnement. La charia est la loi divine idéale ; le fiqh en est l'interprétation humaine."},
{id:"madhhab", t:"Madhhab (école juridique)", c:"isl", m:["madhhab"], n:"madhhab", d:"« Voie » : école de droit musulman. Le sunnisme en reconnaît quatre (hanafite, malikite, chaféite, hanbalite) ; les chiites suivent l'école jaʿfarite."},
{id:"usul", t:"Uṣūl al-fiqh", c:"isl", m:["uṣūl al-fiqh"], n:"chafeite", d:"« Fondements du droit » : méthode qui ordonne les sources du droit (Coran, Sunna, consensus, analogie), théorisée par al-Shāfiʿī."},
{id:"ray", t:"Raʾy", c:"isl", m:["raʾy"], n:"hanafite", d:"« Opinion » : raisonnement personnel du juriste en l'absence de texte ; valorisé par Abū Ḥanīfa, critiqué par les traditionalistes."},
{id:"fatwa", t:"Fatwa", c:"isl", m:["fatwas","fatwa"], d:"Avis juridique rendu par un savant (mufti) en réponse à une question ; il n'a pas, par lui-même, force de loi."},
{id:"mufti", t:"Mufti", c:"isl", m:["mufti"], d:"Juriste habilité à rendre des fatwas ; le « grand mufti » est l'autorité religieuse officielle d'un pays."},
{id:"cadi", t:"Cadi", c:"isl", m:["cadi","Cadi"], cs:true, d:"Juge musulman qui applique le droit (fiqh)."},
{id:"oulemas", t:"Oulémas", c:"isl", m:["oulémas","ouléma"], d:"« Savants » : spécialistes du Coran, du hadith et du droit, qui forment le corps religieux de l'islam."},
{id:"mujtahid", t:"Mujtahid · ayatollah · marjaʿ", c:"isl", m:["mujtahid","ayatollahs","ayatollah","marjaʿ"], n:"duodecimains", d:"Chez les chiites duodécimains, le mujtahid est le juriste qualifié pour interpréter la loi ; les plus éminents portent le titre d'ayatollah (« signe de Dieu ») ; le marjaʿ (« source à imiter ») est celui que chaque fidèle choisit de suivre."},
{id:"velayat", t:"Velāyat-e faqīh", c:"isl", m:["velāyat-e faqīh"], n:"khomeini", d:"« Gouvernement du juriste » : doctrine de Khomeiny selon laquelle, en l'absence de l'Imam caché, un juriste chiite doit diriger l'État. Fondement de la République islamique d'Iran (1979)."},
{id:"mihna", t:"Miḥna", c:"isl", m:["Miḥna"], cs:true, n:"mamun", d:"« Épreuve » : inquisition des califes abbassides (833-848) qui obligent juges et savants à professer que le Coran est créé ; Ibn Ḥanbal résiste."},
{id:"corancree", t:"Coran créé ou incréé", c:"isl", m:["Coran créé","Coran incréé"], cs:true, d:"Débat théologique : le Coran est-il une création de Dieu dans le temps (thèse muʿtazilite) ou sa parole éternelle, incréée (thèse qui l'emporte chez les sunnites) ?"},
{id:"kalam", t:"Kalām", c:"isl", m:["kalām"], n:"kalam", d:"Théologie musulmane : défense rationnelle de la foi (unicité et attributs de Dieu, statut du Coran, liberté humaine)."},
{id:"falsafa", t:"Falsafa", c:"isl", m:["falsafa"], n:"falsafa", d:"La philosophie en terre d'islam, héritière des Grecs traduits à Bagdad : al-Kindī, al-Fārābī, Avicenne, Averroès."},
{id:"soufisme", t:"Soufisme", c:"isl", m:["soufisme","soufi","soufis","soufie","soufies"], n:"soufisme", d:"Mystique de l'islam : recherche de l'union à Dieu par l'ascèse, l'amour et le souvenir de Dieu (dhikr) ; organisée en confréries à partir du XIIe s."},
{id:"tariqa", t:"Ṭarīqa (confrérie)", c:"isl", m:["ṭarīqa","confrérie","confréries"], n:"confreries", d:"« Voie » : confrérie soufie organisée autour d'un maître (cheikh) et d'une chaîne spirituelle qui remonte au Prophète."},
{id:"derviche", t:"Derviche", c:"isl", m:["derviches","derviche"], n:"rumi", d:"« Pauvre » en persan : membre d'une confrérie soufie. Les derviches tourneurs sont les Mevlevis, disciples de Rūmī."},
{id:"wahdat", t:"Waḥdat al-wujūd", c:"isl", m:["waḥdat al-wujūd"], n:"ibnarabi", d:"« Unicité de l'être » : doctrine attribuée à Ibn ʿArabī, pour qui seul Dieu existe vraiment, le monde étant sa manifestation ; Ibn Taymiyya la juge panthéiste."},
{id:"tawhid", t:"Tawḥīd", c:"isl", m:["tawḥīd"], d:"« Unification » : affirmation de l'unicité absolue de Dieu, cœur de la foi musulmane ; le wahhabisme en fait son mot d'ordre."},
{id:"salaf", t:"Salaf · salafisme", c:"isl", m:["salaf","salafisme","salafiste","salafistes"], n:"ibntaymiyya", d:"« Pieux devanciers » : les trois premières générations de musulmans. Le salafisme veut revenir à leur islam supposé pur, en rejetant les innovations, le soufisme et les traditions locales."},
{id:"jahiliyya", t:"Jāhiliyya", c:"isl", m:["jāhiliyya"], n:"qutb", d:"« Ignorance » : nom donné par les musulmans à l'Arabie païenne d'avant l'islam. Sayyid Quṭb l'applique aux sociétés musulmanes modernes, qu'il juge impies."},
{id:"hanif", t:"Ḥanīf", c:"isl", m:["ḥanīf"], d:"Dans le Coran, monothéiste originel, « ni juif ni chrétien », comme Abraham. Des ḥanīf auraient existé en Arabie avant l'islam."},
{id:"kaaba", t:"Kaaba", c:"isl", m:["Kaaba"], cs:true, d:"Sanctuaire cubique de La Mecque, vers lequel les musulmans prient ; selon le Coran, il fut bâti par Abraham et Ismaël. La Pierre noire est enchâssée dans l'un de ses angles."},
{id:"zamzam", t:"Zamzam", c:"isl", m:["Zamzam"], cs:true, n:"ismael", d:"Source sacrée de La Mecque, jaillie selon la tradition pour Hājar (Agar) et Ismaël assoiffés."},
{id:"hajj", t:"Pèlerinage (ḥajj)", c:"isl", m:[], auto:false, d:"Pèlerinage à La Mecque, obligatoire une fois dans la vie pour qui le peut ; ses rites rappellent Abraham, Hājar et Ismaël (course entre Ṣafā et Marwa, sacrifice)."},
{id:"aid", t:"Aïd al-Adha", c:"isl", m:["Aïd al-Adha"], cs:true, n:"abraham", d:"« Fête du sacrifice » : grande fête musulmane qui commémore le fils d'Abraham épargné par Dieu ; on y sacrifie un mouton."},
{id:"achoura", t:"Achoura", c:"isl", m:["Achoura"], cs:true, n:"husayn", d:"Le 10 du mois de muḥarram : pour les chiites, deuil de la mort d'al-Ḥusayn à Karbalāʾ (680), avec processions et récits de sa passion ; jour de jeûne facultatif chez les sunnites."},
{id:"arbain", t:"Arbaʿīn", c:"isl", m:["Arbaʿīn"], cs:true, n:"husayn", d:"« Quarantième » jour après Achoura : pèlerinage à Karbalāʾ, l'un des plus grands rassemblements humains au monde."},
{id:"ansar", t:"Anṣār", c:"isl", m:["Anṣār"], cs:true, n:"ansar", d:"« Les Auxiliaires » : musulmans de Médine qui accueillent Mahomet en 622, aux côtés des « Émigrés » (muhājirūn) venus de La Mecque."},
{id:"quraysh", t:"Quraysh", c:"isl", m:["Quraysh"], cs:true, n:"fihr", d:"Tribu marchande qui domine La Mecque et sa Kaaba au VIe s. Mahomet en est issu, comme tous les califes jusqu'aux Abbassides."},
{id:"hachemites", t:"Hachémites", c:"isl", m:["Hachémites","hachémite"], cs:true, n:"hashim", d:"Descendants de Hāshim, arrière-grand-père de Mahomet ; aujourd'hui la famille royale de Jordanie."},
{id:"omeyyades", t:"Omeyyades", c:"isl", m:["Omeyyades","omeyyade","omeyyades"], cs:true, n:"umayya", d:"Dynastie issue d'Umayya, clan de Quraysh : califes de Damas (661-750), puis émirs et califes de Cordoue (756-1031)."},
{id:"abbassides", t:"Abbassides", c:"isl", m:["Abbassides","abbasside","abbassides"], cs:true, n:"abbas", d:"Dynastie issue d'al-ʿAbbās, oncle du Prophète : califes de Bagdad (750-1258), puis califes sans pouvoir au Caire (1261-1517)."},
{id:"fatimides", t:"Fatimides", c:"isl", m:["Fatimides","fatimide","fatimides"], cs:true, n:"fatimides", d:"Dynastie ismaélienne qui se réclame de Fāṭima : califes en Ifrīqiya (Tunisie), puis au Caire, qu'ils fondent (909-1171)."},
{id:"ayyoubides", t:"Ayyoubides", c:"isl", m:["Ayyoubides","ayyoubide"], cs:true, n:"saladin", d:"Dynastie kurde sunnite fondée par Saladin, qui règne sur l'Égypte et la Syrie (1171-1250)."},
{id:"mamelouks", t:"Mamelouks", c:"isl", m:["Mamelouks","mamelouks","mamelouke","mamelouk"], cs:true, d:"Soldats d'origine servile (turcs, circassiens) qui prennent le pouvoir en Égypte et en Syrie (1250-1517) ; ils arrêtent les Mongols et chassent les derniers croisés."},
{id:"ottomans", t:"Ottomans", c:"isl", m:["Ottomans","ottoman","ottomane","ottomanes"], cs:true, n:"ottomans", d:"Dynastie turque (~1299-1922) qui prend Constantinople (1453) et domine les Balkans, le Proche-Orient et l'Afrique du Nord ; ses sultans portent le titre de calife jusqu'en 1924."},
{id:"safavides", t:"Safavides", c:"isl", m:["Safavides","safavide"], cs:true, n:"safavides", d:"Dynastie qui impose le chiisme duodécimain en Iran (1501-1736)."},
{id:"almohades", t:"Almohades", c:"isl", m:["Almohades","almohade"], cs:true, n:"almohades", d:"Dynastie berbère du Maghreb et d'al-Andalus (1121-1269), à la doctrine rigoriste de l'unicité divine."},
{id:"kunya", t:"Kunya", c:"isl", m:["kunya"], d:"Surnom arabe formé sur le nom d'un enfant, souvent le fils aîné : Abū l-Qāsim, « le père d'al-Qāsim », pour Mahomet."},
{id:"batin", t:"Bāṭin", c:"isl", m:["bāṭin"], n:"ismaelisme", d:"« Intérieur, caché » : sens ésotérique du Coran, accessible aux initiés selon les ismaéliens, par opposition au sens apparent (ẓāhir)."},
{id:"dawa", t:"Daʿwa", c:"isl", m:["daʿwa"], d:"« Appel » : prédication missionnaire, et réseau de propagande clandestine des Abbassides et des ismaéliens."},
{id:"injil", t:"Tawrāt · Zabūr · Injīl", c:"isl", m:["Injīl","Zabūr","Tawrāt"], cs:true, d:"Livres révélés avant le Coran selon l'islam : la Tawrāt (Torah) à Moïse, le Zabūr (Psaumes) à David, l'Injīl (Évangile) à Jésus. Le Coran reproche aux juifs et aux chrétiens d'en avoir altéré le sens."},
{id:"namus", t:"Nāmūs", c:"isl", m:["Nāmūs"], cs:true, d:"Du grec nomos, « loi » : dans la Sīra, Waraqa reconnaît dans l'ange de la révélation le « Nāmūs » venu jadis à Moïse."},
{id:"negus", t:"Négus", c:"chr", m:["Négus"], cs:true, d:"Titre du roi chrétien d'Éthiopie (Aksoum). Vers 615, il accueille des musulmans persécutés à La Mecque : la « première hégire »."},
{id:"sceau", t:"Sceau des prophètes", c:"isl", m:["sceau des prophètes"], n:"mahomet", d:"Titre de Mahomet (Coran 33,40) : il clôt la lignée des prophètes. Mani s'était déjà proclamé « sceau des prophètes »."},
{id:"meres", t:"Mères des croyants", c:"isl", m:["Mères des croyants","mère des croyants"], cs:true, n:"epouses", d:"Titre honorifique des épouses de Mahomet (Coran 33,6)."},
{id:"constitution", t:"Constitution de Médine", c:"isl", m:["Constitution de Médine"], cs:true, d:"Pacte conclu à Médine après l'hégire entre les émigrés de La Mecque, les tribus de Médine et leurs alliés juifs : la communauté (umma) y apparaît comme une entité à la fois religieuse et politique."},
{id:"shura", t:"Shūrā", c:"isl", m:["shūrā"], d:"« Consultation » : principe coranique de décision collective ; ʿUmar confie le choix de son successeur à un conseil de six compagnons."},
{id:"ismaeliens", t:"Ismaéliens", c:"isl", m:["Ismaéliens","ismaéliens","ismaélienne","ismaélien","septimains"], cs:true, n:"ismaelisme", d:"Chiites qui suivent la lignée d'Ismāʿīl, fils de Jaʿfar al-Ṣādiq (d'où « septimains » : ils se séparent au septième imam). Fatimides, nizârites de l'Aga Khan, Bohras."},
{id:"duodecimains", t:"Duodécimains", c:"isl", m:["duodécimains","duodécimain"], n:"duodecimains", d:"Chiites qui reconnaissent douze imams, le dernier étant caché depuis 874 : la grande majorité des chiites (Iran, Irak, Liban…)."},
{id:"zaydites", t:"Zaydites", c:"isl", m:["zaydites","zaydite"], n:"zaydisme", d:"Chiites qui suivent Zayd ibn ʿAlī : l'imam est tout descendant d'ʿAlī et Fāṭima qui se lève contre l'injustice. Surtout au Yémen."},
{id:"wahhabisme", t:"Wahhabisme", c:"isl", m:["wahhabite","wahhabites"], n:"wahhabisme", d:"Doctrine rigoriste de Muḥammad ibn ʿAbd al-Wahhāb (XVIIIe s.), alliée à la dynastie saoudienne : tawḥīd intransigeant, rejet du culte des saints."},
{id:"arabes", t:"Arabes ʿāriba et mustaʿriba", c:"isl", m:["mustaʿriba","ʿāriba"], d:"Distinction des généalogistes : Arabes « purs » (ʿāriba) du Sud, issus de Qaḥṭān, et Arabes « arabisés » (mustaʿriba) du Nord, issus d'Ismaël par ʿAdnān."},
{id:"sabeens", t:"Sabéens (du Coran)", c:"isl", m:["Sabéens"], cs:true, n:"mandeens", d:"Groupe religieux que le Coran cite à côté des juifs et des chrétiens (2,62) ; souvent identifié aux mandéens. À ne pas confondre avec les habitants du royaume de Saba."},
{id:"hedjaz", t:"Hedjaz", c:"his", m:["Hedjaz"], cs:true, d:"Région de l'ouest de l'Arabie, le long de la mer Rouge, où se trouvent La Mecque et Médine."},
{id:"yathrib", t:"Yathrib", c:"his", m:["Yathrib"], cs:true, d:"Ancien nom de Médine, devenue après l'hégire « la ville (du Prophète) », madīnat al-nabī."},

/* histoire et archéologie */
{id:"historicite", t:"Historicité", c:"his", m:["historicité"], d:"Le fait d'avoir réellement existé ou eu lieu, établi par des sources indépendantes (archéologie, textes extérieurs). Dans l'arbre, le remplissage de chaque repère indique ce degré."},
{id:"anachronisme", t:"Anachronisme", c:"his", m:["anachronisme","anachronismes"], d:"Détail qui ne correspond pas à l'époque où se situe le récit (des chameaux domestiqués au temps d'Abraham, par exemple) : c'est l'indice d'une rédaction plus tardive."},
{id:"stele", t:"Stèle", c:"his", m:["stèle","stèles"], d:"Pierre dressée portant une inscription, souvent royale ou commémorative."},
{id:"ostracon", t:"Ostracon", c:"his", m:["ostracon","Ostraca","ostraca"], cs:true, d:"Tesson de poterie utilisé pour écrire (au pluriel : ostraca)."},
{id:"bulle", t:"Bulle (sceau)", c:"his", m:["bulle","bulles"], d:"Petite pastille d'argile portant l'empreinte d'un sceau, qui fermait un document ; elle peut porter le nom d'un roi ou d'un fonctionnaire."},
{id:"papyrus", t:"Papyrus", c:"his", m:["papyrus"], d:"Support d'écriture fait de fibres d'une plante du Nil ; il ne se conserve que dans les climats secs."},
{id:"parchemin", t:"Parchemin", c:"his", m:["parchemin","parchemins"], d:"Peau animale préparée pour l'écriture. Le carbone 14 date la mort de l'animal, pas le moment où l'on a écrit."},
{id:"palimpseste", t:"Palimpseste", c:"his", m:["palimpseste"], d:"Manuscrit dont le premier texte a été gratté pour en écrire un autre ; on peut parfois lire le texte effacé, par exemple aux ultraviolets."},
{id:"codex", t:"Codex", c:"his", m:["codex"], d:"Livre fait de feuillets pliés et cousus, et non plus un rouleau. Le « codex de ʿUthmān » est la version officielle du Coran."},
{id:"c14", t:"Carbone 14", c:"his", m:["carbone 14","C14"], cs:true, d:"Méthode de datation des matières organiques (parchemin, bois, os) par la décroissance radioactive du carbone 14 ; la marge d'erreur est de quelques décennies."},
{id:"paleographie", t:"Paléographie", c:"his", m:["paléographique","paléographie"], d:"Datation d'un manuscrit d'après la forme de son écriture ; moins précise que le carbone 14."},
{id:"ossuaire", t:"Ossuaire", c:"his", m:["ossuaire","ossuaires"], d:"Coffret de pierre où l'on rassemblait les os d'un défunt, un an après l'inhumation : pratique juive de Jérusalem entre ~20 av. et 70 apr. J.-C."},
{id:"annales", t:"Annales", c:"his", m:["annales"], d:"Récits officiels des campagnes royales, année par année (Assyrie, Babylonie) ; ils citent plusieurs rois d'Israël et de Juda."},
{id:"prisme", t:"Prisme", c:"his", m:["prisme"], d:"Prisme ou cylindre d'argile couvert d'écriture cunéiforme, portant les annales d'un roi (prisme de Sennachérib)."},
{id:"tell", t:"Tell", c:"his", m:["Tell","Tel"], cs:true, d:"Colline artificielle formée par les ruines superposées d'une ville antique (arabe tell, hébreu tel) ; le mot entre dans de nombreux noms de sites."},
{id:"ironI", t:"Âge du fer I (Iron I)", c:"his", m:["Iron I"], cs:true, n:"juges", d:"Période d'environ 1200 à 1000 av. J.-C., quand apparaissent les villages des premiers Israélites dans les hautes terres ; l'âge du bronze la précède."},
{id:"chronologie", t:"Chronologie haute ou basse", c:"his", m:["chronologie basse","chronologie haute"], n:"david", d:"Débat d'archéologues sur la datation des couches des Xe–IXe s. av. J.-C. La chronologie « basse » (Finkelstein) rajeunit de quelques décennies les monuments attribués à David et Salomon, et réduit leur royaume."},
{id:"levant", t:"Levant", c:"his", m:["Levant"], cs:true, d:"Rive orientale de la Méditerranée : Syrie, Liban, Israël, Palestine, Jordanie."},
{id:"mesopotamie", t:"Mésopotamie", c:"his", m:["Mésopotamie","mésopotamien","mésopotamiens","mésopotamienne"], cs:true, d:"« Entre les fleuves » : la plaine du Tigre et de l'Euphrate (Irak actuel), berceau de Sumer, d'Akkad, de Babylone et de l'Assyrie."},
{id:"assyrie", t:"Assyrie", c:"his", m:["Assyrie","Assyriens","assyrien","assyriens","assyrienne","assyriennes"], cs:true, d:"Empire du nord de la Mésopotamie (capitale Ninive) qui domine le Proche-Orient aux IXe–VIIe s. av. J.-C. ; il détruit le royaume d'Israël en 722."},
{id:"babylone", t:"Babylone", c:"his", m:["Babylone","babylonien","babylonienne","Babyloniens"], cs:true, n:"exil", d:"Ville et empire de Mésopotamie. Sous Nabuchodonosor II, il détruit Jérusalem (587/586 av. J.-C.) et déporte ses élites ; le Perse Cyrus le conquiert en 539."},
{id:"perse", t:"Perse", c:"his", m:["Perse","Perses"], cs:true, d:"L'Iran ancien : l'Empire achéménide (550-330 av. J.-C.), qui autorise le retour des exilés juifs, puis l'Empire sassanide (224-651), rival de Rome et de Byzance, conquis par les Arabes."},
{id:"sassanides", t:"Sassanides", c:"his", m:["Sassanides","sassanides","sassanide"], cs:true, d:"Dernière dynastie perse avant l'islam (224-651), zoroastrienne ; elle s'effondre devant les conquêtes arabes (al-Qādisiyya, 636)."},
{id:"byzance", t:"Byzance", c:"his", m:["Byzance","byzantin","byzantins","Byzantins","byzantine","byzantines"], cs:true, d:"Nom donné par les historiens à l'Empire romain d'Orient, chrétien et de langue grecque, dont la capitale est Constantinople (330-1453)."},
{id:"hellenise", t:"Hellénisé · hellénistes", c:"his", m:["hellénisés","hellénisé","hellénistes","hellénistique"], d:"Influencé par la culture grecque, répandue au Proche-Orient après Alexandre le Grand (IVe s. av. J.-C.). Les « hellénistes » des Actes des Apôtres sont des juifs de langue grecque."},
{id:"ethnarque", t:"Ethnarque · tétrarque", c:"his", m:["ethnarque","tétrarque","Tétrarque"], cs:true, d:"Titres de princes vassaux de Rome : l'ethnarque gouverne un peuple ; le tétrarque une partie (« un quart ») d'un royaume partagé, comme celui d'Hérode."},
{id:"prefet", t:"Préfet de Judée", c:"his", m:["préfet"], d:"Gouverneur romain d'une petite province comme la Judée (6-41 apr. J.-C.) ; c'est le titre de Ponce Pilate, qu'on appelait autrefois « procurateur »."},
{id:"philistins", t:"Philistins", c:"his", m:["Philistins"], cs:true, d:"Peuple venu du monde égéen, installé sur la côte de Canaan vers 1175 av. J.-C. (Gaza, Ashdod…), adversaire d'Israël. Le nom « Palestine » en dérive."},
{id:"shasou", t:"Shasou", c:"his", m:["Shasou"], cs:true, n:"jethro", d:"Nom égyptien des nomades de Transjordanie et du Néguev (XVe–XIIe s. av. J.-C.)."},
{id:"amorrites", t:"Amorrites", c:"his", m:["amorrites","Amorrites"], cs:true, d:"Peuples sémites de Syrie et de Mésopotamie au IIe millénaire av. J.-C. ; leurs noms ressemblent à ceux des patriarches bibliques."},
{id:"sudarabique", t:"Sudarabique", c:"his", m:["sudarabiques","sudarabique"], n:"saba", d:"Du sud de l'Arabie (Yémen) : royaumes de Saba et de Ḥimyar, leur langue et leur écriture propre."},
{id:"testimonium", t:"Testimonium flavianum", c:"his", m:["Testimonium"], cs:true, n:"jesus", d:"Passage de Flavius Josèphe sur Jésus (Antiquités juives 18,63-64), retouché par des copistes chrétiens ; la plupart des historiens pensent qu'un noyau authentique existait."}
];

/* ---------- références ---------- */
/* abréviation, nom français, nom anglais (pour la lecture en ligne), testament */
const BIBLE = {
  'Gn':['Genèse','Genesis','AT'], 'Ex':['Exode','Exodus','AT'], 'Lv':['Lévitique','Leviticus','AT'], 'Nb':['Nombres','Numbers','AT'],
  'Dt':['Deutéronome','Deuteronomy','AT'], 'Jos':['Josué','Joshua','AT'], 'Jg':['Juges','Judges','AT'], 'Rt':['Ruth','Ruth','AT'],
  '1 S':['1er livre de Samuel','1 Samuel','AT'], '2 S':['2e livre de Samuel','2 Samuel','AT'], '1 R':['1er livre des Rois','1 Kings','AT'],
  '2 R':['2e livre des Rois','2 Kings','AT'], '1 Ch':['1er livre des Chroniques','1 Chronicles','AT'], '2 Ch':['2e livre des Chroniques','2 Chronicles','AT'],
  'Esd':['Esdras','Ezra','AT'], 'Ne':['Néhémie','Nehemiah','AT'], 'Jb':['Job','Job','AT'], 'Ps':['Psaumes','Psalms','AT'],
  'Pr':['Proverbes','Proverbs','AT'], 'Is':['Isaïe','Isaiah','AT'], 'Jr':['Jérémie','Jeremiah','AT'], 'Ez':['Ézéchiel','Ezekiel','AT'],
  'Dn':['Daniel','Daniel','AT'], 'Os':['Osée','Hosea','AT'], 'Am':['Amos','Amos','AT'], 'Jon':['Jonas','Jonah','AT'],
  'Ag':['Aggée','Haggai','AT'], 'Za':['Zacharie','Zechariah','AT'], 'Ml':['Malachie','Malachi','AT'],
  'Mt':['Évangile selon Matthieu','Matthew','NT'], 'Mc':['Évangile selon Marc','Mark','NT'], 'Lc':['Évangile selon Luc','Luke','NT'],
  'Jn':['Évangile selon Jean','John','NT'], 'Ac':['Actes des Apôtres','Acts','NT'], 'Rm':['Épître aux Romains','Romans','NT'],
  '1 Co':['1re épître aux Corinthiens','1 Corinthians','NT'], '2 Co':['2e épître aux Corinthiens','2 Corinthians','NT'],
  'Ga':['Épître aux Galates','Galatians','NT'], 'Ph':['Épître aux Philippiens','Philippians','NT'],
  '1 Th':['1re épître aux Thessaloniciens','1 Thessalonians','NT'], 'He':['Épître aux Hébreux','Hebrews','NT'],
  'Ap':['Apocalypse','Revelation','NT']
};
/* livres cités en toutes lettres suivis d'une référence entre parenthèses */
const BIBLE_FULL = {'Genèse':'Gn', 'Deutéronome':'Dt', 'Matthieu':'Mt'};
const SURAS = ['', 'al-Fātiḥa','al-Baqara','Āl ʿImrān','al-Nisāʾ','al-Māʾida','al-Anʿām','al-Aʿrāf','al-Anfāl','al-Tawba','Yūnus',
  'Hūd','Yūsuf','al-Raʿd','Ibrāhīm','al-Ḥijr','al-Naḥl','al-Isrāʾ','al-Kahf','Maryam','Ṭā-Hā',
  'al-Anbiyāʾ','al-Ḥajj','al-Muʾminūn','al-Nūr','al-Furqān','al-Shuʿarāʾ','al-Naml','al-Qaṣaṣ','al-ʿAnkabūt','al-Rūm',
  'Luqmān','al-Sajda','al-Aḥzāb','Sabaʾ','Fāṭir','Yā-Sīn','al-Ṣāffāt','Ṣād','al-Zumar','Ghāfir',
  'Fuṣṣilat','al-Shūrā','al-Zukhruf','al-Dukhān','al-Jāthiya','al-Aḥqāf','Muḥammad','al-Fatḥ','al-Ḥujurāt','Qāf',
  'al-Dhāriyāt','al-Ṭūr','al-Najm','al-Qamar','al-Raḥmān','al-Wāqiʿa','al-Ḥadīd','al-Mujādila','al-Ḥashr','al-Mumtaḥana',
  'al-Ṣaff','al-Jumuʿa','al-Munāfiqūn','al-Taghābun','al-Ṭalāq','al-Taḥrīm','al-Mulk','al-Qalam','al-Ḥāqqa','al-Maʿārij',
  'Nūḥ','al-Jinn','al-Muzzammil','al-Muddaththir','al-Qiyāma','al-Insān','al-Mursalāt','al-Nabaʾ','al-Nāziʿāt','ʿAbasa',
  'al-Takwīr','al-Infiṭār','al-Muṭaffifīn','al-Inshiqāq','al-Burūj','al-Ṭāriq','al-Aʿlā','al-Ghāshiya','al-Fajr','al-Balad',
  'al-Shams','al-Layl','al-Ḍuḥā','al-Sharḥ','al-Tīn','al-ʿAlaq','al-Qadr','al-Bayyina','al-Zalzala','al-ʿĀdiyāt',
  'al-Qāriʿa','al-Takāthur','al-ʿAṣr','al-Humaza','al-Fīl','Quraysh','al-Māʿūn','al-Kawthar','al-Kāfirūn','al-Naṣr',
  'al-Masad','al-Ikhlāṣ','al-Falaq','al-Nās'];
/* références juives et anciennes citées dans les fiches */
const OTHER_REFS = {
  'Shabbat 31a':['Talmud de Babylone','Traité Shabbat, feuillet 31, recto (a).','https://www.sefaria.org/Shabbat.31a'],
  'Sanhédrin 4,5':['Michna','Traité Sanhédrin, chapitre 4, paragraphe 5.','https://www.sefaria.org/Mishnah_Sanhedrin.4.5'],
  'Pirqé Avot 1,1':['Michna','Traité Avot (« Maximes des Pères »), chapitre 1, paragraphe 1 : la « chaîne de la tradition ».','https://www.sefaria.org/Pirkei_Avot.1.1'],
  'Genèse Rabba 38':['Midrash','Genèse Rabba (Bereshit Rabba), commentaire rabbinique de la Genèse (Ve s.), section 38 : Abraham et les idoles de son père.','https://www.sefaria.org/Bereshit_Rabbah.38'],
  'Antiquités 18,116-119':['Flavius Josèphe','Antiquités juives (~93), livre 18, paragraphes 116 à 119 : l\'exécution de Jean le Baptiste.',null],
  'Antiquités 20,200':['Flavius Josèphe','Antiquités juives (~93), livre 20, paragraphe 200 : la lapidation de Jacques, « frère de Jésus appelé Christ ».',null],
  'Antiquités 18,63-64':['Flavius Josèphe','Antiquités juives (~93), livre 18, paragraphes 63 et 64 : le passage sur Jésus (Testimonium flavianum).',null]
};

/* ---------- liens dans les textes ----------
   Les noms d'entrées cités dans les fiches deviennent des liens. MENTION_ADD ajoute des formes courtes,
   MENTION_SKIP écarte les formes ambiguës, GUARDS neutralise des expressions où un nom ne désigne pas l'entrée. */
const MENTION_ADD = {
  'Jacob':'jacob', 'Israël':null, 'Jésus':'jesus', 'Jean-Baptiste':'jeanbaptiste', 'Marie':'josephmarie', 'Hérode':'herode',
  'ʿAlī':'ali', 'ʿUthmān':'uthman', 'ʿUmar':'umar', 'Abū Bakr':'abubakr', 'Muʿāwiya':'muawiya', 'Yazīd':'yazid', 'Ḥusayn':'husayn',
  'Fāṭima':'fatima', 'ʿĀʾisha':'aisha', 'Khadīja':'khadija', 'Avicenne':'ibnsina', 'Averroès':'ibnrushd', 'Rachi':'rachi',
  'Hillel':'hillel', 'Shammaï':'shammai', 'Aqiva':'aqiva', 'Augustin':'augustin', 'Paul':'paul', 'Pierre':'pierre', 'Haman':'haman',
  'Nicée':'nicee', 'Chalcédoine':'chalcedoine', 'Éphèse':'ephese', 'Réforme':'reforme1517', 'Vatican II':'vatican2', 'Vatican I':'vatican1',
  'Ibn Ḥanbal':'hanbalite', 'Abū Ḥanīfa':'hanafite', 'Mālik':null, 'al-Shāfiʿī':'chafeite', 'Ibn Taymiyya':'ibntaymiyya',
  'Mahomet':'mahomet', 'Moïse':'moise', 'Abraham':'abraham', 'Isaac':'isaac', 'Ismaël':'ismael', 'Ésaü':'esau', 'Noé':'noe',
  'Adam':'adam', 'Ève':'adam', 'Abel':'abel', 'Caïn':'cain', 'Seth':'seth', 'Sem':'sem', 'Cham':'cham', 'Japhet':'japhet',
  'Saül':'saul', 'Salomon':'salomon', 'David':'david', 'Élie':'elie', 'Élisée':'elisee', 'Isaïe':'isaie', 'Jérémie':'jeremie',
  'Ézéchiel':'ezechiel', 'Jonas':'jonas', 'Daniel':'daniel', 'Samuel':'samuel', 'Aaron':'aaron', 'Myriam':'myriam', 'Josué':'josue',
  'Esther':'esther', 'Mardochée':'esther', 'Ruth':'ruth', 'Booz':'booz', 'Jessé':'jesse', 'Zorobabel':'zorobabel', 'Jojakin':'jojakin',
  'Ézéchias':'ezechias', 'Josias':'josias', 'Achab':'achab', 'Jézabel':'achab', 'Omri':'omri', 'Jéhu':'jehu', 'Athalie':'athalie',
  'Roboam':'roboam', 'Achaz':'achaz', 'Ozias':'ozias', 'Sédécias':'sedecias', 'Joaqim':'joaqim', 'Mésha':'mesha', 'Jéthro':'jethro',
  'Loth':'loth', 'Térah':'terah', 'Rébecca':'rebecca', 'Léa':'lea', 'Rachel':'rachel', 'Laban':'laban', 'Hénoch':'henoch',
  'Mathusalem':'mathusalem', 'Éber':'eber', 'Nimrod':'nimrod', 'Qédar':'qedar', 'Nebayoth':'nebayoth', 'ʿAdnān':'adnan',
  'Caïphe':'caiphe', 'Hérode Antipas':'antipas', 'Agrippa Ier':'agrippa1', 'Jean le Baptiste':'jeanbaptiste',
  'Marie de Magdala':'magdala', 'Judas Iscariote':'judas', 'Jacques le Juste':'jacques', 'Gamaliel':'gamaliel1',
  'Juda ha-Nassi':'judanassi', 'Yohanan ben Zakkaï':'yohanan', 'Siméon bar Yohaï':'baryohai', 'Saadia Gaon':'saadia',
  'Maïmonide':'maimonide', 'Nahmanide':'nahmanide', 'Juda Halévi':'halevi', 'Sabbataï Tsevi':'sabbatai', 'Sabbataï':'sabbatai',
  'Baal Shem Tov':'hassidisme', 'Mendelssohn':'haskala', 'Herzl':'sionisme', 'Khomeiny':'khomeini', 'Saladin':'saladin',
  'al-Ḥākim':'hakim', 'al-Maʾmūn':'mamun', 'Hārūn al-Rashīd':'harun', 'al-Manṣūr':'mansur', 'al-Mutawakkil':'mutawakkil',
  'Abū Sufyān':'abusufyan', 'Abū Jahl':'abujahl', 'Abū Ṭālib':'abutalib', 'Abū Lahab':'abulahab', 'Ḥamza':'hamza',
  'al-ʿAbbās':'abbas', 'Ibn ʿAbbās':'ibnabbas', 'Ibn al-Zubayr':'ibnzubayr', 'al-Zubayr':'zubayr', 'Ḥafṣa':'hafsa',
  'Khālid ibn al-Walīd':'khalid', 'ʿAmr ibn al-ʿĀṣ':'amrouas', 'Waraqa':'waraqa', 'Hāshim':'hashim', 'Quṣayy':'qusayy',
  'ʿAbd al-Muṭṭalib':'abdmuttalib', 'Āmina':'amina', 'Jaʿfar al-Ṣādiq':'jafar', 'Zayd ibn ʿAlī':'zayd', 'ʿAlī al-Riḍā':'rida',
  'Mūsā al-Kāẓim':'kazim', 'Ismāʿīl':'ismail', 'ʿAbd al-Malik':'abdalmalik', 'Marwān II':'marwan2', 'Hind':'hind',
  'al-Ghazālī':'ghazali', 'Ibn ʿArabī':'ibnarabi', 'Rūmī':'rumi', 'al-Ḥallāj':'hallaj', 'al-Ashʿarī':'asharisme',
  'Ibn Rushd':'ibnrushd', 'Ibn Sīnā':'ibnsina', 'Sayyid Quṭb':'qutb', 'Ḥasan al-Bannā':'freres',
  'Luther':'luther', 'Calvin':'calvin', 'Zwingli':'zwingli', 'Wesley':'methodisme', 'Henri VIII':'anglicanisme',
  'Arius':'arianisme', 'Marcion':'marcion', 'Mani':'manicheisme', 'Constantin':'milan', 'Théodose':'thessalonique',
  'Irénée':'irenee', 'Polycarpe':'irenee', 'Jean Damascène':'damascene', 'Pélage':'pelagianisme', 'Jan Hus':'hus',
  'Thomas':null, 'Jean':null, 'Joseph':null, 'Jacques':null, 'Simon':null, 'Juda':'juda', 'Canaan':'canaan',
  'Qumrân':'esseniens', 'Masada':'zelotes', 'Talmud':null, 'al-Mahdī':null, 'Mahdī':null, 'Karbalāʾ':null,
  'Jean Hyrcan':'hyrcan1', 'Mariamne':'mariamne', 'Mésha':'mesha', 'Théologie':null, 'Philosophie':null, 'Persécutions':null,
  'Épouses':null, 'Alexandrie':null, 'Anne':null, 'Joas':null, 'Ilyās':null, 'Diaspora':null, 'Exil':null, 'Ibrāhīm':null
};
/* expressions où le nom ne renvoie pas à l'entrée correspondante */
const GUARDS = ['Temple de Hambourg','Pierre noire','Pierre de Pilate','Isaac Louria','Abraham Geiger','Moïse de León','Moses Mendelssohn',
  'Jacques Ier','Jacques Baradée','Juda ben Tabbaï','Samuel ha-Naguid','Grégoire le Grand','Exode palestinien','Pablo Christiani',
  'Simon-Pierre','Simon le Zélote','Jacques d\'Alphée','Jean-Paul II','Paul VI','Muḥammad ibn ʿAbd al-Wahhāb','Muḥammad ibn Saʿūd',
  'Muḥammad ʿAbduh','Muḥammad ibn Ismāʿīl','ʿUbayd Allāh al-Mahdī','Ḥusayn ibn ʿAlī','Ḥamza ibn ʿAlī','Joseph Smith',
  'Moïse Isserlès','Shāh Ismāʿīl','Thomas d\'Aquin','Zacharias Frankel','Māriya la Copte','Anan ben David',
  'Saint-Pierre','Saint-Jean-Baptiste','Saint-Sépulcre','Saint-Barthélemy','Sainte-Sophie','Hailé Sélassié','Bob Marley','Marcus Garvey',
  'Mustafa Kemal','Charles Martel','Shema, serviteur','Élie de Vilna','Réforme religieuse','Réforme contre','Réforme deutéronomiste'];
/* homonymes : dans la fiche d'une entrée donnée, une forme renvoie ailleurs (ou nulle part : null) */
const MENTION_NODE_MAP = {
  henochc:{'Hénoch':null}, mtline:{'Éléazar':null},
  heli:{'Jacob':'jacobmt', 'Joseph':'josephmarie'}, jacques:{'Joseph':'josephmarie'},
  juda:{'Joseph':'joseph'}, manasse:{'Joseph':'joseph'}, rachel:{'Joseph':'joseph'},
  caiphe:{'Jacques':'jacques'}, jesus:{'Jacques':'jacques'}, agrippa1:{'Jacques':'jean'}, douze:{'Jacques':'jean'},
  irenee:{'Jean':'jean'}, mandeens:{'Jean':'jeanbaptiste'}
};

/* ---------- parcours guidés ---------- */
const TOURS = [
{id:"origines", t:"Aux origines", s:"D'Adam à Abraham", c:"c", steps:[
 ["adam","Tout commence ici : le premier couple de la Genèse et du Coran. Les dates « AM » suivent le calendrier traditionnel juif, pas l'histoire : regardez le repère vide, il signale une figure connue par la tradition seule."],
 ["abel","Premier drame de l'humanité : Caïn tue Abel. Le Coran en tire une maxime que l'on trouve déjà dans la Michna — tuer une âme, c'est tuer l'humanité entière."],
 ["seth","Seth remplace Abel. C'est par lui que passe la longue lignée qui mène, génération après génération, jusqu'à Noé."],
 ["henoch","Hénoch « marcha avec Dieu » et disparut sans mourir. L'Église éthiopienne lit le livre qui porte son nom ; la tradition musulmane l'identifie souvent au prophète Idrīs."],
 ["noe","Noé, seul juste sauvé du Déluge. Le récit reprend un mythe mésopotamien plus ancien : comparez avec la tablette XI de l'épopée de Gilgamesh."],
 ["sem","De Sem, le fils béni, viennent les « Sémites » — un mot inventé en 1781 pour une famille de langues, pas pour une race."],
 ["eber","Éber donne son nom aux « Hébreux ». Ici l'arbre bifurque : son fils Yoqtân devient, pour les généalogistes arabes, Qaḥṭān, l'ancêtre des Arabes du Sud."],
 ["terah","Térah quitte Ur pour Harran. Le Midrash et le Coran en font un fabricant d'idoles, réfuté par son propre fils."],
 ["abraham","Abraham, le patriarche commun : les trois grandes branches de l'arbre partent de lui. Touchez « Déplier toute la branche » pour voir l'ampleur de sa descendance."]
]},
{id:"abraham", t:"Abraham et ses fils", s:"Une famille, trois héritages", c:"c", steps:[
 ["abraham","Chaque religion revendique Abraham : père du peuple juif par Isaac, « père des croyants » pour Paul, ḥanīf « ni juif ni chrétien » pour le Coran."],
 ["ismael","Ismaël, l'aîné, fils de la servante égyptienne Agar. Prophète en islam, il bâtit la Kaaba avec son père et passe pour l'ancêtre des Arabes du Nord."],
 ["qedar","Les « fils d'Ismaël » ne sont pas que des noms : Qédar, Nebayoth, Douma ou Téma sont des peuples et des oasis bien réels, connus des annales assyriennes."],
 ["isaac","Isaac, le fils de la promesse, lié sur l'autel puis épargné. Mais quel fils fut offert ? La Genèse dit Isaac ; la plupart des exégètes musulmans, Ismaël."],
 ["jacob","Isaac a des jumeaux. Jacob capte la bénédiction, reçoit le nom d'Israël, et ses douze fils deviennent les douze tribus."],
 ["esau","Ésaü, le jumeau évincé, ancêtre des Édomites. Pour les rabbins, « Édom » finira par désigner Rome, puis la chrétienté."],
 ["keturah","On l'oublie souvent : Abraham a six autres fils, de Qetoura, ancêtres de peuples d'Arabie comme les Madianites."],
 ["adnan","Bien plus tard, ʿAdnān. Entre Ismaël et lui, les listes varient ; à partir de lui, toutes les sources donnent la même chaîne jusqu'à Mahomet."],
 ["mahomet","Au bout de cette lignée : Mahomet, « sceau des prophètes » pour l'islam. Ouvrez sa lignée en bas de la fiche pour remonter jusqu'à Adam."]
]},
{id:"moise", t:"Moïse et la Loi", s:"De l'Égypte aux Prophètes", c:"j", steps:[
 ["levi","La tribu de Lévi, sans territoire, est vouée au culte. C'est d'elle que viennent Moïse, Aaron et tous les prêtres."],
 ["amram","Amram et Yokébed, parents de Myriam, d'Aaron et de Moïse : le Coran parle de la « famille d'ʿImrān »."],
 ["moise","Le prophète le plus cité du Coran, figure centrale de la Bible. Mais aucune trace égyptienne de l'Exode : c'est ici que le récit et l'histoire se séparent nettement."],
 ["aaron","Aaron, premier grand prêtre. La bénédiction sacerdotale qu'on lui attribue est gravée sur le plus ancien fragment biblique connu (~600 av. J.-C.)."],
 ["sinai","Le don de la Torah ouvre la « chaîne de la tradition » : de Moïse à Josué, aux Anciens, aux Prophètes… jusqu'aux rabbins. Remarquez le trait en tirets : une transmission, pas une filiation."],
 ["josue","Josué conquiert Canaan — un récit théologique : à Jéricho et à Aï, les fouilles ne montrent pas de ville fortifiée vers 1200 av. J.-C."],
 ["juges","L'époque des Juges coïncide avec l'apparition de centaines de villages dans les collines, sans os de porc : une identité israélite se forme sur place."],
 ["prophetes","Les Prophètes affrontent rois et peuple. C'est chez eux, surtout pendant l'Exil, que se formule le monothéisme strict : « hors moi, pas de Dieu »."]
]},
{id:"david", t:"De David à Jésus", s:"La lignée royale et messianique", c:"j", steps:[
 ["jesse","« Un rameau sortira de la souche de Jessé » : cette prophétie a donné l'« arbre de Jessé » des vitraux médiévaux — l'ancêtre de l'arbre que vous parcourez."],
 ["david","Le roi-berger. La stèle de Tel Dan (~840 av. J.-C.) mentionne la « maison de David » : sa dynastie est attestée, l'étendue de son royaume reste débattue."],
 ["salomon","Le bâtisseur du Premier Temple, à la sagesse proverbiale. Aucune inscription ne le nomme encore."],
 ["roboam","Sous son fils Roboam, le royaume se brise : dix tribus forment au nord le royaume d'Israël, Juda reste à la dynastie de David."],
 ["ezechias","Ézéchias résiste au siège assyrien de 701 : le prisme de Sennachérib raconte qu'il l'a enfermé « comme un oiseau en cage »."],
 ["josias","Josias centralise le culte à Jérusalem : un seul Temple pour un seul Dieu. Une étape décisive vers le monothéisme exclusif."],
 ["exil","587/586 av. J.-C. : Jérusalem est détruite et ses élites déportées à Babylone. Ce désastre devient le creuset du judaïsme."],
 ["zorobabel","Au retour d'Exil, Zorobabel rebâtit le Temple : c'est le dernier descendant de David à exercer le pouvoir."],
 ["josephmarie","Matthieu et Luc rattachent Joseph à David… par deux généalogies différentes. Comparez avec l'entrée « Héli (lignée de Luc) »."],
 ["jesus","Jésus de Nazareth : prédicateur juif pour l'historien, Messie et Fils de Dieu pour les chrétiens, prophète ʿĪsā pour l'islam. Le trait épais et creux indique une filiation légale."]
]},
{id:"rabbins", t:"Le judaïsme des rabbins", s:"Survivre sans le Temple", c:"j", steps:[
 ["grandeassemblee","Après l'Exil, Esdras fait de la Torah la loi du peuple. La tradition y place la « Grande Assemblée », maillon de la chaîne de transmission."],
 ["zougot","Cinq générations de « Paires » de maîtres transmettent l'enseignement, jusqu'à Hillel et Shammaï."],
 ["pharisiens","Les pharisiens étendent la sainteté à la vie quotidienne et croient en la résurrection : ce sont les ancêtres directs des rabbins."],
 ["hillel","« Ce qui t'est détestable, ne le fais pas à ton prochain : c'est toute la Torah, le reste est commentaire. »"],
 ["yohanan","70 : le Temple brûle. Yohanan ben Zakkaï obtient l'école de Yavné — le judaïsme devient religion de l'étude et de la prière."],
 ["aqiva","Rabbi Aqiva, le plus grand maître de son temps, salue Bar Kokhba comme Messie et meurt martyr en récitant le Shema."],
 ["judanassi","Vers 200, Juda ha-Nassi met par écrit la Torah orale : c'est la Michna."],
 ["talmudb","Trois siècles de débats sur la Michna donnent le Talmud de Babylone, autorité suprême du judaïsme."],
 ["rachi","Rachi, vigneron champenois, écrit les commentaires imprimés depuis dans toutes les éditions de la Bible et du Talmud."],
 ["maimonide","Maïmonide, né à Cordoue, médecin au Caire : un code de toute la loi juive et un « Guide des égarés » qui concilie la Torah et Aristote."],
 ["hassidisme","Au XVIIIe s., le hassidisme propose une piété joyeuse et fervente — et déclenche l'opposition des mitnagdim."],
 ["sionisme","Face aux pogroms et à l'affaire Dreyfus, le sionisme de Herzl veut un État juif. Il divise les religieux eux-mêmes."]
]},
{id:"chretiens", t:"Des apôtres aux Églises", s:"Vingt siècles de christianisme", c:"x", steps:[
 ["jeanbaptiste","Jean le Baptiste, prophète du désert, baptise Jésus. Flavius Josèphe confirme son exécution par Hérode Antipas."],
 ["jesus","Jésus annonce le Royaume de Dieu ; il est crucifié sous Ponce Pilate vers 30. Les historiens s'accordent sur son existence, son baptême et sa crucifixion."],
 ["pierre","Pierre, premier des Douze : « sur cette pierre je bâtirai mon Église ». Les papes se disent ses successeurs."],
 ["paul","Paul ouvre le mouvement aux non-juifs, sans circoncision. Ses lettres sont les plus anciens textes chrétiens."],
 ["egliseancienne","L'Église ancienne s'organise autour des évêques, fixe son canon… et se sépare peu à peu du judaïsme."],
 ["milan","313 : Constantin accorde la liberté de culte. Persécutée hier, l'Église devient bientôt religion de l'Empire."],
 ["nicee","325, Nicée : le Fils est « consubstantiel » au Père. Arius est condamné, mais la crise dure un siècle."],
 ["chalcedoine","451, Chalcédoine : le Christ est une personne en deux natures. Une grande partie de l'Orient refuse et forme les Églises orthodoxes orientales."],
 ["schisme1054","1054 : Rome et Constantinople s'excommunient. Le Filioque, la primauté du pape et le pain azyme séparent orthodoxes et catholiques."],
 ["reforme1517","1517 : les 95 thèses de Luther. « L'Écriture seule, la grâce seule, la foi seule » : naissance du protestantisme."],
 ["vatican2","1962-1965 : Vatican II. Avec Nostra Aetate, l'Église catholique rejette l'accusation de déicide et tend la main aux juifs et aux musulmans."],
 ["pentecotisme","Aujourd'hui, le pentecôtisme, né en 1906 à Los Angeles, est le courant chrétien qui croît le plus vite au monde."]
]},
{id:"islam", t:"La naissance de l'islam", s:"De La Mecque aux premiers califes", c:"m", steps:[
 ["qusayy","Au Ve s., Quṣayy unifie les clans de Quraysh et prend le contrôle de La Mecque et de la Kaaba, alors sanctuaire païen."],
 ["hashim","Hāshim organise les grandes caravanes d'hiver et d'été ; il donne son nom aux Hachémites."],
 ["abdmuttalib","ʿAbd al-Muṭṭalib redécouvre le puits de Zamzam et tient tête à l'armée éthiopienne lors de « l'année de l'Éléphant »."],
 ["mahomet","Vers 610, dans la grotte de Ḥirāʾ, Mahomet reçoit sa première révélation. L'hégire de 622 ouvre le calendrier musulman."],
 ["khadija","Khadīja, riche négociante, est la première à croire en sa mission. Sa mort en 619 ouvre « l'année de la tristesse »."],
 ["abubakr","À la mort du Prophète (632), Abū Bakr est élu premier calife. Pour les chiites, ʿAlī avait pourtant été désigné."],
 ["umar","ʿUmar conquiert la Syrie, l'Égypte, l'Irak et la Perse, et fixe l'an 1 du calendrier à l'hégire."],
 ["mushaf","Sous ʿUthmān, le texte officiel du Coran est fixé. Les feuillets de Birmingham, datés au carbone 14, sont presque contemporains."],
 ["fitna1","656 : l'assassinat de ʿUthmān ouvre la première guerre civile. L'islam va s'y diviser durablement."],
 ["ali","ʿAlī, cousin et gendre du Prophète : quatrième calife pour les sunnites, premier imam pour les chiites."]
]},
{id:"chiisme", t:"Sunnites et chiites", s:"Comprendre la grande fracture", c:"m", steps:[
 ["fitna1","Tout part d'une question : qui doit diriger la communauté après le Prophète ? La première fitna (656-661) fixe trois réponses."],
 ["kharijites","Les kharijites : le plus pieux, fût-il un esclave. Ils rompent avec ʿAlī — l'un d'eux l'assassine en 661. Seul l'ibadisme (Oman, Mzab) en est issu aujourd'hui."],
 ["sunnisme","Les sunnites : légitimité des quatre premiers califes, autorité de la Sunna et du consensus. Environ 85-90 % des musulmans."],
 ["muawiya","Muʿāwiya fonde le califat omeyyade de Damas et rend le pouvoir héréditaire."],
 ["husayn","680, Karbalāʾ : al-Ḥusayn, petit-fils du Prophète, est tué par l'armée de Yazīd. Ce martyre fonde l'identité chiite."],
 ["jafar","Jaʿfar al-Ṣādiq, sixième imam, grand maître du droit. Sa succession divise les chiites."],
 ["ismaelisme","Les ismaéliens suivent son fils Ismāʿīl : ils fonderont le califat fatimide du Caire et, aujourd'hui, la communauté de l'Aga Khan."],
 ["mahdi","Les autres suivent la lignée jusqu'au douzième imam, caché depuis 874, qui doit revenir à la fin des temps."],
 ["duodecimains","Les duodécimains, majorité des chiites : en l'absence de l'imam, l'autorité revient aux juristes, les ayatollahs."],
 ["madhhab","Côté sunnite, quatre écoles juridiques se partagent le monde musulman et se reconnaissent mutuellement."],
 ["soufisme","Et par-dessus ces frontières, le soufisme, la voie mystique de l'islam, présent chez les sunnites comme chez les chiites."]
]},
{id:"preuves", t:"Ce que dit l'archéologie", s:"Confirmé, nuancé ou démenti", c:"k", steps:[
 ["abraham","Pour les patriarches, aucune trace hors des textes — et des anachronismes : des chameaux domestiqués qui n'arrivent au Levant qu'au Xe s. av. J.-C."],
 ["moise","Ni les plaies d'Égypte ni l'Exode n'ont laissé de traces. La plupart des archéologues font naître Israël sur place, parmi les Cananéens."],
 ["jacob","Première apparition d'« Israël » : la stèle du pharaon Mérenptah, vers 1208 av. J.-C. — comme peuple, pas comme ancêtre."],
 ["mesha","La stèle de Mésha (Louvre) cite Omri, Israël et le nom YHWH : la plus ancienne mention extra-biblique sûre du nom divin."],
 ["david","La stèle de Tel Dan atteste la « maison de David » : pour la première fois, la dynastie sort de la Bible."],
 ["achab","Achab aligne 2 000 chars contre l'Assyrie selon le monolithe de Kurkh : le roi honni de la Bible était une puissance régionale."],
 ["jehu","Sur l'obélisque noir de Salmanazar III, Jéhu (ou son envoyé) se prosterne : la seule image connue d'un roi d'Israël."],
 ["ezechias","Prisme de Sennachérib, reliefs de Lakish, tunnel de Siloé, sceau royal : Ézéchias est l'un des rois les mieux attestés."],
 ["jojakin","Des tablettes de Babylone enregistrent l'huile livrée au roi exilé « Yaʾukinu, roi de Yahudu » : l'Exil est confirmé."],
 ["jesus","Jésus : pas de trace archéologique directe, mais Paul, les évangiles, Josèphe et Tacite. La pierre de Pilate atteste le préfet qui l'a condamné."],
 ["mahomet","Mahomet est mentionné par des sources chrétiennes dès 634-640, avant toute biographie musulmane."],
 ["mushaf","Les feuillets de Birmingham, datés au carbone 14 entre 568 et 645, comptent parmi les plus anciens manuscrits du Coran."]
]},
{id:"conflits", t:"Guerres et dialogues", s:"Quinze siècles de face-à-face", c:"k", steps:[
 ["juifsarabie","À Médine, les tribus juives s'opposent à Mahomet : expulsions, puis exécution des Qurayẓa (627), aux chiffres débattus."],
 ["husayn","680 : Karbalāʾ, la guerre entre musulmans devient le drame fondateur du chiisme."],
 ["abdalmalik","691 : le Dôme du Rocher, sur le Mont du Temple, proclame en arabe le refus de la Trinité."],
 ["croisades","1095-1291 : les croisades. Elles frappent les musulmans, mais aussi les juifs de Rhénanie et les chrétiens de Constantinople."],
 ["saladin","1187 : Saladin reprend Jérusalem, sans massacre."],
 ["mendiants","1219 : en pleine croisade, François d'Assise rencontre pacifiquement le sultan al-Kāmil."],
 ["inquisition","1492 : l'Espagne expulse ses juifs ; l'Inquisition traque les convertis."],
 ["ottomans","1453 : chute de Constantinople. Les Ottomans deviennent la grande puissance sunnite face à l'Europe chrétienne et à l'Iran chiite."],
 ["shoah","1941-1945 : la Shoah. Le nazisme a exploité des siècles d'antijudaïsme chrétien."],
 ["vatican2","1965 : Nostra Aetate ouvre l'ère du dialogue ; en 2019, le pape et le grand imam d'al-Azhar signent à Abu Dhabi un document sur la fraternité humaine."]
]},
{id:"nouvelles", t:"Religions sœurs et filles", s:"Ce qui est né des trois", c:"n", steps:[
 ["samaritains","Les Samaritains, héritiers du royaume du Nord, gardent leur propre Torah et leur montagne sainte depuis plus de 2 500 ans."],
 ["mandeens","Les mandéens vénèrent Jean le Baptiste et rejettent Jésus : un baptisme gnostique venu de l'Antiquité."],
 ["manicheisme","Mani se proclame « sceau des prophètes » après Bouddha, Zoroastre et Jésus ; sa religion s'étend jusqu'en Chine."],
 ["druzes","Les Druzes naissent de la divinisation du calife fatimide al-Ḥākim ; Jéthro est leur grand prophète."],
 ["yezidis","Les Yézidis, issus d'une confrérie soufie, ont été victimes d'un génocide en 2014."],
 ["babisme","La foi bahāʾīe, née du chiisme iranien, se veut universelle ; son centre mondial est à Haïfa."],
 ["ahmadiyya","L'Ahmadiyya, née au Pendjab en 1889, est persécutée au Pakistan, qui la déclare non musulmane."],
 ["restauration","Mormons et Témoins de Jéhovah veulent restaurer l'Église primitive, mais rejettent la Trinité."],
 ["rastafari","Le rastafarisme, né en Jamaïque dans les années 1930, voit en l'empereur d'Éthiopie le Messie."]
]}
];
